DOCS-1945: Magento 1 Connect Settings to Connect Gateways
MultiSafepay/docs pull request #1006
Opened 2021-01-27 14:25 UTC by Atiq-MultiSafepay

2021-01-27 20:34 UTC, Ronald-MultiSafepay requested changes
Since v3.0.0 of the plugin this option is removed from the configurtion as the status is automatic set to shipped for completed orders.

See https://docs.multisafepay.com/integrations/plugins/magento1/changelog/
PLGMAGONE-472: Set order to status shipped for all payment methods

2021-02-02 13:57 UTC, Kris-MultiSafepay requested changes

2021-02-02 13:57 UTC, Kris-MultiSafepay commented on content/integrations/plugins/magento1/faq/ship-automatically-in-magento1.md
> +Within our Magento 1 plugin, all complete orders will automatically be set to the status _Shipped_ . This is needed to capture the money from AfterPay, E-Invoicing, Klarna, Pay After Delivery and San
```suggestion
Within our Magento 1 plugin, all complete orders are automatically set to the status _Shipped_ . This is needed to collect the funds from AfterPay, E-Invoicing, Klarna, Pay After Delivery and Santander Betaal per Maand.
```

2021-03-08 11:40 UTC, Kris-MultiSafepay approved these changes

2021-03-08 11:48 UTC, closed without merging