Docs: lsp update
MultiSafepay/docs pull request #1018
Opened 2021-02-02 12:47 UTC by Lars-MultiSafepay

sup,

for PLGLTS-208 I want to make some changes to the refund page.

2021-03-04 10:48 UTC, Thomas-MultiSafepay commented
@Lars-MultiSafepay Check banned words etc

2021-03-08 12:10 UTC, Kris-MultiSafepay requested changes

2021-03-08 12:10 UTC, Kris-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/refunding-lightspeed.md
> +A shopping has 3 items and 1.70€ shopping cost. If you refund 1 item and 0.40€ this will fail.
```suggestion

- A shopping has 3 items and 1.70€ shopping cost. If you refund 1 item and 0.40€ this will fail. 

```

2021-03-08 12:10 UTC, Kris-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/refunding-lightspeed.md
> +Refunding a item and a amount separately will not cause any issue.
```suggestion
- Refunding an item and an amount separately will not cause any issue.

```

2021-03-08 12:10 UTC, Kris-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/refunding-lightspeed.md
> +If any refund is placed using the lightspeed backend a short message will be placed in the notes section of an order. This message can contain a error if anything happens.
```suggestion
If any refund is placed using the lightspeed backend a short message will be placed in the notes section of an order. This message can contain an error if anything happens.

```

2021-03-08 12:10 UTC, Kris-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/refunding-lightspeed.md
> +Yes you can refund orders as well as credit notes. By default you can create a refund in your [MultiSafepay Control](https://merchant.multisafepay.com), however, refunding directly from your Lightspe
```suggestion
Yes, you can refund orders as well as credit notes. By default, you can create a refund in your [MultiSafepay Control](https://merchant.multisafepay.com), however, refunding directly from your Lightspeed backend is possible.

```

2021-03-08 12:23 UTC, Kris-MultiSafepay requested changes

2021-03-08 12:23 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce integrations/lightspeed_app/faq/refunding-lightspeed.md
> +
```suggestion

```

2021-03-08 12:24 UTC, merged