FAQ item for OpenCart and WooCommerce generic gateway
MultiSafepay/docs pull request #1063
Opened 2021-02-15 09:34 UTC by Daniel-MultiSafepay

This PR includes a short FAQ article for OpenCart and WooCommerce plugins on generic gateways.

The base branch is a generic gateway started by @Thomas-MultiSafepay to unite all the changes related to this concept and submit a PR to master at the right moment.

2021-02-18 14:17 UTC, Kris-MultiSafepay requested changes
Mostly English grammar and rephrasing suggestions.

2021-02-18 14:17 UTC, Kris-MultiSafepay commented on content/integrations/plugins/opencart/faq/generic-gateways.md
> +The OpenCart plugin offer a generic gateway; that can be found in plugin settings page, listed in payment methods tab.
```suggestion
The OpenCart plugin offers a generic gateway. The generic gateway can be found on the plugin settings page, listed in the payment methods tab.
```

2021-02-18 14:17 UTC, Kris-MultiSafepay commented on content/integrations/plugins/opencart/faq/generic-gateways.md
> +All of our payment methods are supported. It is possible to set the gateway code, gateway logo, gateway label and whether the shopping cart should be included in refund transactions; which is require
```suggestion
All of our payment methods are supported. It is possible to set the gateway code, gateway logo, gateway label, and whether the shopping cart should be included in refund transactions. Specifying whether the shopping cart should be included in refund transactions is required if the gateway code used is that of a billing suite payment method.
```

2021-02-18 14:17 UTC, Kris-MultiSafepay commented on content/integrations/plugins/opencart/faq/generic-gateways.md
> +In the same way than others gateways, is possible also filter the generic gateway by geo zone, currency, min amount, max amount, customer groups, and a set a custom initial order status.
```suggestion
Similar to other gateways, it is possible to filter the generic gateway by:

* geographic zone
* currency
* min amount
* max amount
* customer groups

Furthermore, you can set a custom initial order status.
```

2021-02-18 14:17 UTC, Kris-MultiSafepay commented on content/integrations/plugins/woocommerce/faq/generic-gateways.md
> +The OpenCart plugin offer a generic gateway; that can be found in WooCommerce Settings; under payment tab, which list all payment methods.
```suggestion
The OpenCart plugin offers a generic gateway. The generic gateway can be found in your WooCommerce Settings under the payment tab, which lists all payment methods.
```

2021-02-18 14:17 UTC, Kris-MultiSafepay commented on content/integrations/plugins/woocommerce/faq/generic-gateways.md
> +All of our payment methods are supported. It is possible to set the gateway code, gateway logo, gateway label and whether the shopping cart should be included in refund transactions; which is require
```suggestion
All of our payment methods are supported. It is possible to set the gateway code, gateway logo, gateway label, and whether the shopping cart should be included in refund transactions. Specifying whether the shopping cart should be included in refund transactions is required if the gateway code used is that of a billing suite payment method.
```

2021-02-18 14:17 UTC, Kris-MultiSafepay commented on content/integrations/plugins/woocommerce/faq/generic-gateways.md
> +In the same way than others gateways, is possible also filter the payment method by country, min amount, max amount, and a set a custom initial order status.
```suggestion
Similar to other gateways, it is possible to filter the generic gateway by:

* geographic zone
* currency
* min amount
* max amount
* customer groups
Furthermore, you can set a custom initial order status.
```

2021-02-18 14:17 UTC, Kris-MultiSafepay commented on content/integrations/plugins/opencart/faq/generic-gateways.md
> +Full refunding actions and backend orders are fully supported.
```suggestion
Full refunds and backend orders are fully supported.
```

2021-02-18 14:17 UTC, Kris-MultiSafepay commented on content/integrations/plugins/woocommerce/faq/generic-gateways.md
> +Full refunding actions, partial refunds action (except for billing suite payment methods), and backend orders are fully supported.
```suggestion
Full refunds, partial refunds (except for billing suite payment methods), and backend orders are fully supported.
```

2021-02-19 16:03 UTC, Vinod-MultiSafepay requested changes
Small feedback

2021-02-19 16:03 UTC, Vinod-MultiSafepay commented on content/integrations/plugins/woocommerce/faq/generic-gateways.md
> +The OpenCart plugin offer a generic gateway; that can be found in WooCommerce Settings; under payment tab, which list all payment methods.
I think OpenCart here should be WooCommerce

2021-03-18 13:43 UTC, Daniel-MultiSafepay commented on content/integrations/plugins/woocommerce/faq/generic-gateways.md
> +The OpenCart plugin offer a generic gateway; that can be found in WooCommerce Settings; under payment tab, which list all payment methods.
Thanks Vinod. ! Is done now.

2021-03-18 13:47 UTC, Vinod-MultiSafepay approved these changes

2021-03-19 12:33 UTC, merged