Docs 1764
MultiSafepay/docs pull request #1075
Opened 2021-02-16 15:53 UTC by Kris-MultiSafepay

### Basic
- We only accept documentation that is proved to work on our LIVE API
- At least 1 approval is needed before pull requests can be merged
- The article must match our Synonym word list. For external commits, a MultiSafepay employee will check
- US English must be applied
- Use bullets for numerations where the sort order doesn't matter. For chronological order, use numbers. This does not apply to changelogs
- Set link on email address.

### Text style
- Paths are written like: _Configuration → System → Plugin → MultiSafepay_
- Use single quotation marks in your Markdown code (example title: 'Title of the article')
- Use Italics for buttons, clicks, paths, etc. Do mind to close the italics before the end of a sentence followed by a period
- Numerations / bullets are punctuated with a period at the end of the numerations / bullets.
- Periods should be excluded for sentences that finish in an e-mail address (e.g. "..contact us at <example@example.com> "  )

### Images
- Screenshot recomended sizes: Width: 820px - Height: auto

### Aliases
- When renaming or deleting a page, add an alias of the renamed or deleted page to the page users should be redirected to instead. This prevents external links to return 404 errors. Check the [Hugo Documentation](https://gohugo.io/content-management/urls/#aliases) for more information.

2021-02-16 17:35 UTC, Kris-MultiSafepay commented on content/tools/transactions-api-endpoint/_index.md
> +If you have any issues or questions, [contact our integration team](mailto:integration@multisafepay.com)
```suggestion
If you have any issues or questions, [contact our Integration team](mailto:integration@multisafepay.com)
```

2021-02-16 17:36 UTC, Kris-MultiSafepay commented on content/tools/transactions-api-endpoint/_index.md
> +If you have any issues or questions, [contact our Integration team](mailto:integration@multisafepay.com)
```suggestion
If you have any issues or questions, [contact our Integration Team](mailto:integration@multisafepay.com)
```

2021-02-17 14:57 UTC, Atiq-MultiSafepay requested changes

2021-02-17 14:57 UTC, Atiq-MultiSafepay commented on content/tools/transactions-api-endpoint/_index.md
> +The transactions API endpoint returns the data of transactions under your account. Using this endpoint, you can automate business operations by matching records at a transaction level. This page prov
The transactions API endpoint returns the data of transactions that are associated with your account. By using this endpoint, you can automate business operations by matching records at a transaction level. This page provides information about the endpoint and its usage.

2021-02-18 09:26 UTC, Kris-MultiSafepay commented on content/tools/transactions-api-endpoint/_index.md
> +The transactions API endpoint returns the data of transactions under your account. Using this endpoint, you can automate business operations by matching records at a transaction level. This page prov
```suggestion
The transactions API endpoint returns the data of transactions under your account. Using this endpoint, you can automate business operations by matching records at a transaction level. This page provides information about the endpoint and its usage.
```

2021-02-23 16:11 UTC, merged