Docs: add more information about graph QL and PWA integration fro Magento 2
MultiSafepay/docs pull request #1090
Opened 2021-02-18 15:49 UTC by Stanislau-MultiSafepay

2021-02-18 16:33 UTC, Vinod-MultiSafepay requested changes
I sugggested some improvements. Maybe it is also a good idea to let Kris review it. He has even better english knowledge then i have.

2021-02-18 16:33 UTC, Vinod-MultiSafepay commented on content/integrations/plugins/magento2/faq/pwa-support.md
> +Yes, plugin fully compatible with GraphQL queries and it's easy possible to integrate into your PWA store with our additional separate [module for GraphQL support](https://github.com/MultiSafepay/mag
```
Yes, the plugin is fully compatible with GraphQL queries and it is possible to easily integrate it into your PWA store with an additional separate [module for GraphQL support](https://github.com/MultiSafepay/magento2-graphql)
```

2021-02-18 16:33 UTC, Vinod-MultiSafepay commented on content/integrations/plugins/magento2/manual.md
> +- Magento Open Source version 2.2.x & 2.3.x & 2.4.x (For GraphQL support Magento Open Source version 2.4.x)
- Magento Open Source version 2.2.x & 2.3.x & 2.4.x (For GraphQL only Magento Open Source version 2.4.x is supported)

2021-02-18 16:33 UTC, Vinod-MultiSafepay commented on content/integrations/pwa/pwa-studio/_index.md
> +description : "Easily integrate MultiSafepay payment solutions into your PWA webshop with the free and completely new MultiSafepay plugin for GraphQL queries support"
I would ditch the word 'support' and say something like:

`description : "Easily integrate MultiSafepay payment solutions into your PWA webshop with the free and completely new MultiSafepay plugin for GraphQL queries and mutations"`

or

`description : "Easily integrate MultiSafepay payment solutions into your PWA webshop with the free and completely new MultiSafepay plugin for GraphQL"`

2021-02-18 16:33 UTC, Vinod-MultiSafepay commented on content/integrations/pwa/pwa-studio/_index.md
> +title_short: "PWA Studio,  ScandiPWA and other"
Maybe change it to either one of these:

`title_short: "PWA Studio,  ScandiPWA and others"`

`title_short: "PWA Studio,  ScandiPWA and more"`

2021-02-18 16:33 UTC, Vinod-MultiSafepay commented on content/integrations/pwa/pwa-studio/manual.md
> +### Integrate into PWA store using a separate extension for GraphQL support
I would say something like this (up to you to change it or not):

`### Integrate into PWA store using a separate extension that adds GraphQL support`

2021-02-18 16:33 UTC, Vinod-MultiSafepay commented on content/integrations/pwa/pwa-studio/manual.md
> +Please see our GitHub repo for the [integration instruction and GraphQL request examples](https://github.com/MultiSafepay/magento2-graphql) for PWA based stores.
`Please see our GitHub repo for the [integration instructions and GraphQL request examples](https://github.com/MultiSafepay/magento2-graphql) for PWA based stores.`

2021-02-18 16:33 UTC, Vinod-MultiSafepay commented on content/integrations/pwa/pwa-studio/manual.md
> +Please, keep in mind that you will be need create a custom payment component for PWA storefront, depends from which you are using.
Please keep in mind that you will need to create a custom payment component for PWA storefront, depending on which PWA storefront you are using.

2021-03-11 13:35 UTC, Kris-MultiSafepay requested changes

2021-03-11 13:35 UTC, Kris-MultiSafepay commented on content/integrations/plugins/magento2/faq/pwa-support.md
> +Yes, the plugin is fully compatible with GraphQL queries and it is possible to easily integrate it into your PWA store with an additional separate [module for GraphQL support](https://github.com/Mult
```suggestion
Yes, the plugin is compatible with GraphQL queries and easy to integrate into your PWA store with an additional [module for GraphQL support](https://github.com/MultiSafepay/magento2-graphql)
```

2021-03-25 13:41 UTC, merged