DOCS-2044: Adjustment to Lightspeed refund information
MultiSafepay/docs pull request #1151
Opened 2021-03-05 08:43 UTC by Atiq-MultiSafepay

2021-03-05 09:44 UTC, Kris-MultiSafepay requested changes

2021-03-05 09:44 UTC, Kris-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/refunding-lightspeed.md
> +To allow refunds from the Lightspeed backend, you first have to enable the following setting. Log in to [lightspeed.multisafepay.com](https://lightspeed.multisafepay.com/settings), scroll down to _En
Do users scroll down to _Enable Refunds_ **or** click _Enable refunds_ in the sidebar? Or do they do both? And if it's **or**; how does scrolling down enable the settings? Also, is 'refunds' once capitalized and once not?

2021-03-05 09:44 UTC, Kris-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/refunding-lightspeed.md
> +Yes you can refund orders as well as credit notes. By default, you can create a refund in your [MultiSafepay Control](https://merchant.multisafepay.com) However, refunds issued from the MultiSafepay
```suggestion
Yes, you can refund orders as well as credit notes. By default, you can create a refund in your [MultiSafepay Control](https://merchant.multisafepay.com). However, refunds issued from the MultiSafepay Control will not be reflected in your Lightspeed backend.

```

2021-06-08 08:31 UTC, FrancescaNCook commented on content/integrations/hosted/lightspeed_app/faq/refunding-lightspeed.md
> +To allow refunds from the Lightspeed backend, you first have to enable the following setting. Log in to [lightspeed.multisafepay.com](https://lightspeed.multisafepay.com/settings), scroll down to _En
Changed to:
To enable refunds from your Lightspeed backend, follow these steps:

1. Log in to lightspeed.multisafepay.com.
2. Go to **Settings**.
3. In the sidebar, click **Enable refunds**.

2021-06-08 08:34 UTC, closed without merging