added information about PWA studio integration
MultiSafepay/docs pull request #1221
Opened 2021-04-07 10:24 UTC by Stanislau-MultiSafepay

### Basic
- We only accept documentation that is proven to work on our LIVE API
- At least one approval is needed before pull requests can be merged
- All content is written in US English
- The terminology used must be in accordance with our naming conventions

### Text style
- Paths are formatted like: _Configuration → System → Plugin → MultiSafepay_
- Use single quotation marks in the front matter of markdown files (e.g., title: 'Title of the article')
- Use _italics_ when describing GUI elements (e.g., buttons, links and paths)
- When a sentence ends with an email address, don't use a period (e.g. "[...] contact us at <example@example.com>")

### Images
- Screenshot recommended sizes: Width: 820px - Height: auto

### Aliases
- When renaming or deleting a page, add an alias of the deprecated URL to the page users should be redirected to. This prevents external links from returning 404 errors. Check the [Hugo Documentation](https://gohugo.io/content-management/urls/#aliases) for more information.

2021-04-08 12:58 UTC, Vinod-MultiSafepay requested changes

2021-04-08 12:58 UTC, Vinod-MultiSafepay commented on content/integrations/pwa/pwa-studio/manual.md
> +- Installed <a href="https://github.com/MultiSafepay/magento2-graphql" target="_blank">MultiSafepay Magento 2 GraphQL</a> plugin for support GraphQL queries.
I would change  `plugin for support GraphQL queries.` to something like: `plugin for supporting GraphQL queries.` or `plugin to add support for GraphQL queries.`

2021-04-08 12:58 UTC, Vinod-MultiSafepay commented on content/integrations/pwa/pwa-studio/manual.md
> +- Meet other requirements for PWA Studio (Venia) and Magento on <a href="https://magento.github.io/pwa-studio/venia-pwa-concept/setup/#prerequisites" target="_blank">official Magento PWA Docs</a>
`the official Magento PWA Docs`

2021-04-08 12:58 UTC, Vinod-MultiSafepay commented on content/integrations/pwa/pwa-studio/manual.md
> +If you would like to install the MultiSafepay plugin into your PWA Stuidio application, please use this [installation instructions](https://github.com/MultiSafepay/pwastudio-multisafepay-payment-inte
typo: `Stuidio` should be `Studio`

2021-04-08 12:58 UTC, Vinod-MultiSafepay commented on content/integrations/pwa/pwa-studio/manual.md
> +If you would like to install the MultiSafepay plugin into your PWA Stuidio application, please use this [installation instructions](https://github.com/MultiSafepay/pwastudio-multisafepay-payment-inte
`If you would like to install the MultiSafepay plugin into your PWA Stuidio application, please use these [installation instructions]`

instructions is plural, so 'these' should be used here instead of 'this'

2021-04-12 11:45 UTC, Kris-MultiSafepay approved these changes

2021-04-12 11:45 UTC, merged