Docs 2210
MultiSafepay/docs pull request #1228
Opened 2021-04-09 14:22 UTC by FrancescaNCook

### Basic
- We only accept documentation that is proven to work on our LIVE API
- At least one approval is needed before pull requests can be merged
- All content is written in US English
- The terminology used must be in accordance with our naming conventions

### Text style
- Paths are formatted like: _Configuration → System → Plugin → MultiSafepay_
- Use single quotation marks in the front matter of markdown files (e.g., title: 'Title of the article')
- Use _italics_ when describing GUI elements (e.g., buttons, links and paths)
- When a sentence ends with an email address, don't use a period (e.g. "[...] contact us at <example@example.com>")

### Images
- Screenshot recommended sizes: Width: 820px - Height: auto

### Aliases
- When renaming or deleting a page, add an alias of the deprecated URL to the page users should be redirected to. This prevents external links from returning 404 errors. Check the [Hugo Documentation](https://gohugo.io/content-management/urls/#aliases) for more information.

2021-04-12 10:06 UTC, Kris-MultiSafepay requested changes

2021-04-12 10:06 UTC, Kris-MultiSafepay commented on content/faq/getting-started/onboarding-new-merchants.md
> +* minimum order value.
```suggestion
* Minimum order value
```

2021-04-12 10:06 UTC, Kris-MultiSafepay commented on content/faq/getting-started/onboarding-new-merchants.md
> +* average order value.
```suggestion
* Average order value
```

2021-04-12 10:06 UTC, Kris-MultiSafepay commented on content/faq/getting-started/onboarding-new-merchants.md
> +* maximum order value.
```suggestion
* Maximum order value
```

2021-04-12 10:06 UTC, Kris-MultiSafepay commented on content/faq/getting-started/onboarding-new-merchants.md
> +* annual turnover in credit card transactions.
```suggestion
* Annual turnover in credit card transactions
```

2021-04-12 10:06 UTC, Kris-MultiSafepay commented on content/faq/getting-started/prohibited-products-and-services.md
> +meta_title: "FAQ Getting Started - Forbidden products/services - MultiSafepay Docs"
```suggestion
meta_title: "FAQ Getting Started - Prohibited products and services - MultiSafepay Docs"
```

2021-04-12 10:06 UTC, Kris-MultiSafepay commented on content/faq/getting-started/ultimate-beneficial-owner-form.md
> +meta_title: "FAQ Getting Started - What is UBO - MultiSafepay Docs"
I am not really liking this meta title

2021-04-12 10:06 UTC, Kris-MultiSafepay commented on content/faq/getting-started/activating-payment-methods.md
> +meta_title: "FAQ Getting Started - Enable payment methods - MultiSafepay Docs"
```suggestion
meta_title: "FAQ Getting Started - Activating payment methods - MultiSafepay Docs"
```

2021-04-12 10:06 UTC, Kris-MultiSafepay commented on content/faq/getting-started/conditions-for-selling-alcohol.md
> +meta_title: "FAQ Getting Started - What are the conditions for selling alcohol? - MultiSafepay Docs"
```suggestion
meta_title: "FAQ Getting Started - Conditions for selling alcohol - MultiSafepay Docs"
```

2021-04-12 10:06 UTC, Kris-MultiSafepay commented on content/faq/getting-started/paying-out-your-multisafepay-control-balance-to-your-business-bank-account.md
> +meta_title: "FAQ Getting Started - Withdraw balance - MultiSafepay Docs"
```suggestion
meta_title: "FAQ Getting Started - Payout out your balance - MultiSafepay Docs"
```

2021-04-12 14:34 UTC, FrancescaNCook commented on content/faq/getting-started/ultimate-beneficial-owner-form.md
> +meta_title: "FAQ Getting Started - What is UBO - MultiSafepay Docs"
What does the meta title do? Is it visible to anyone?

2021-04-12 14:35 UTC, FrancescaNCook commented on content/faq/getting-started/paying-out-your-multisafepay-control-balance-to-your-business-bank-account.md
> +meta_title: "FAQ Getting Started - Withdraw balance - MultiSafepay Docs"
Change to "Paying out your balance"?

2021-04-12 14:38 UTC, FrancescaNCook commented on content/faq/getting-started/testing-with-multisafepay.md
> +### 4. Client server updates transaction status
Not sure what you mean by "handles"? Do you mean "processes", "sends", "saves"?

2021-04-12 14:39 UTC, FrancescaNCook commented on content/faq/getting-started/testing-with-multisafepay.md
> +4.  Client system updates the transaction status.
As in other comment, clarify intended meaning of "handles".

2021-04-12 14:40 UTC, FrancescaNCook commented on content/faq/getting-started/testing-with-multisafepay.md
> +3.  MultiSafepay sends a status change notification.
Yes, great. Just a period at the end please :)

2021-04-12 14:41 UTC, FrancescaNCook commented on content/faq/getting-started/testing-with-multisafepay.md
> +1.  Merchant initiates an order.
Yes, but with a period because it's a complete sentence.

2021-04-12 14:41 UTC, FrancescaNCook commented on content/faq/getting-started/testing-with-multisafepay.md
> +2.  Customer completes the payment.
Yes, but with a period because it's a complete sentence.

2021-04-12 14:43 UTC, FrancescaNCook commented on content/faq/getting-started/testing-with-multisafepay.md
> +{{< /alert-notice >}}
What is the difference between an alert notice and a blue notice? Is it documented anywhere?

2021-04-12 14:45 UTC, FrancescaNCook commented on content/faq/getting-started/_index.md
> +This section contains all the information you need to start processing payments with MultiSafepay.
Agreed. I don't really like introductory sentences that say nothing. Hopefully it should be evident from your information design.

2021-04-13 07:23 UTC, Kris-MultiSafepay commented on content/faq/getting-started/ultimate-beneficial-owner-form.md
> +meta_title: "FAQ Getting Started - What is UBO - MultiSafepay Docs"
Good that you ask, they rendered as [<title> tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title). These are displayed as the label on the tab in a web browser, as well as the title of search engine results, browser bookmark, etc.

2021-04-13 07:23 UTC, Kris-MultiSafepay commented on content/faq/getting-started/paying-out-your-multisafepay-control-balance-to-your-business-bank-account.md
> +meta_title: "FAQ Getting Started - Withdraw balance - MultiSafepay Docs"
Yes!

2021-04-14 06:58 UTC, FrancescaNCook commented on content/faq/getting-started/ultimate-beneficial-owner-form.md
> +meta_title: "FAQ Getting Started - What is UBO - MultiSafepay Docs"
Ah right, then I think we should make them match the filename, which may be a slightly shorter version of the page title. What do you think?

2021-04-15 14:38 UTC, Kris-MultiSafepay requested changes

2021-04-15 14:38 UTC, Kris-MultiSafepay commented on content/faq/getting-started/onboarding-new-merchants.md
> +You can upload all of the required documents and information in your MultiSafepay Control account → [Onboarding flow](https://merchant.multisafepay.com/onboarding):
```suggestion
You can upload all of the required documents and information in your MultiSafepay Control > [Business details](https://merchant.multisafepay.com/onboarding):
```

2021-04-15 14:38 UTC, Kris-MultiSafepay commented on content/faq/getting-started/onboarding-new-merchants.md
> +You can upload all of the required documents and information in your MultiSafepay Control account → [Onboarding flow](https://merchant.multisafepay.com/onboarding):
Even though the URL suggests it's named onboarding, the heading of the page is 'Business details', so we should probably match that.
<img width="1171" alt="Screenshot 2021-04-15 at 16 17 25" src="https://user-images.githubusercontent.com/73658536/114884455-12f57280-9e06-11eb-83d9-d749531a5199.png">

2021-04-15 14:38 UTC, Kris-MultiSafepay commented on content/faq/getting-started/conditions-for-selling-alcohol.md
> +Merchants must also submit a Merchant declaration regarding alcoholic beverages (once only). Email a signed copy of the declaration to the Risk Team at <risk@multisafepay.com>. Download the:
```suggestion
Merchants must also submit a Merchant declaration regarding alcoholic beverages (once only). Email a signed copy of the declaration to the Risk Team at <risk@multisafepay.com>.

Download the:
```
<img width="681" alt="Screenshot 2021-04-15 at 16 26 11" src="https://user-images.githubusercontent.com/73658536/114885787-4be21700-9e07-11eb-9008-eea9657a7ed3.png">

2021-04-15 14:43 UTC, Kris-MultiSafepay commented on content/faq/getting-started/paying-out-your-balance.md
> +meta_title: "FAQ Getting Started - Withdraw balance - MultiSafepay Docs"
```suggestion
meta_title: "FAQ Getting Started - Paying out your balance - MultiSafepay Docs"
```

2021-04-15 14:46 UTC, Kris-MultiSafepay commented on content/faq/getting-started/ultimate-beneficial-owner-form.md
> +meta_title: "FAQ Getting Started - What is UBO - MultiSafepay Docs"
```suggestion
meta_title: "FAQ Getting Started - Ultimate Beneficial Owner form - MultiSafepay Docs"
```

2021-04-15 14:58 UTC, merged