Add FAQ for recommended tax settings inside Magento 2
MultiSafepay/docs pull request #1254
Opened 2021-04-22 14:59 UTC by Vinod-MultiSafepay

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2021-04-22 18:09 UTC, Stanislau-MultiSafepay requested changes
one small thing

2021-04-22 18:09 UTC, Stanislau-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> +title : "Which tax settings should i use?"
Maybe "i" should be capital?

2021-04-29 15:17 UTC, Stanislau-MultiSafepay approved these changes

2021-05-04 12:30 UTC, Kris-MultiSafepay requested changes

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> +To prevent discrepancies between item amounts inside the MultiSafepay transactions and Magento orders, we recommend to use certain tax settings inside Magento.
```suggestion
To prevent discrepancies between item amounts inside MultiSafepay transactions and Magento orders, we recommend you to use certain tax settings inside Magento.
```

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> +Tax settings in Magento can be found under _Stores_ > _Configuration_ > _Sales_ > _Tax_ > _Calculation Settings_
```suggestion
Tax settings in Magento can be found under **Stores** > **Configuration** > **Sales** > **Tax** > **Calculation Settings**
```

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> +If you want to show prices **excluding tax**, we recommend the following settings:
```suggestion
If you want to show prices **excluding tax**, use the following settings:
```

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> ++ _Tax Calculation Method Based On_: Row Total
```suggestion
+ **Tax Calculation Method Based On**: Row Total
```

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> ++ _Catalog Prices_: Excluding Tax
```suggestion
+ **Catalog Prices**: Excluding Tax
```

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> ++ _Apply Customer Tax_: After Discount
```suggestion
+ **Apply Customer Tax**: After Discount
```

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> ++ _Apply Discount On Prices_: Excluding Tax
```suggestion
+ **Apply Discount On Prices**: Excluding Tax
```

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> +For stores that want to show prices **including tax**, we recommend the following settings:
```suggestion
If you want to show prices **including tax**, use the following settings:
```

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> ++ _Tax Calculation Method Based On_: Row Total
```suggestion
+ **Tax Calculation Method Based On**: Row Total
```

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> ++ _Catalog Prices_: Including Tax
```suggestion
+ **Catalog Prices**: Including Tax
```

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> ++ _Apply Customer Tax_: After Discount
```suggestion
+ **Apply Customer Tax**: After Discount
```

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> ++ _Apply Discount On Prices_: Including Tax
```suggestion
+ **Apply Discount On Prices**: Including Tax
```

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> +meta_title: "Magento 2 payment link - MultiSafepay Docs"
```suggestion
meta_title: "Magento 2 - Recommended tax settings - MultiSafepay Docs"
```

2021-05-04 12:30 UTC, Kris-MultiSafepay commented on content/integrations/ecommerce-integrations/magento2/faq/which-tax-settings-should-i-use.md
> +We also recommend to look at the recommendations from Magento, as our settings should be in line with the [Magento recommendations](https://docs.magento.com/user-guide/tax/warning-messages.html).
```suggestion
Our recommended settings are based on Magento's standards. For more information, see [Magento's documentation on tax settings](https://docs.magento.com/user-guide/tax/warning-messages.html).
```

2021-05-04 12:41 UTC, merged