DOCS-1294: Remove duplication in item description
MultiSafepay/docs pull request #1279
Opened 2021-05-18 07:59 UTC by FrancescaNCook

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2021-05-24 15:22 UTC, Kris-MultiSafepay requested changes
Good changes, but I don't see an implementation of Ross' suggestions

2021-05-24 15:22 UTC, Kris-MultiSafepay commented on content/api/payment_methods/post_order_afterpay.md
> +Text displayed with the order in your MultiSafepay Control, and on the customer's bank statement (if supported by the bank). Max. 200 characters. HTML is not supported. Use the `items` or `shopping_c
```suggestion
Text displayed with the order in your MultiSafepay Control, and on the customer's bank statement (if supported by the bank). Max. 200 characters. HTML formatting is not supported. To add descriptions in HTML format, use the `items` or `shopping_cart` objects instead.
```

2021-05-24 15:22 UTC, Kris-MultiSafepay commented on content/api/payment_methods/post_order_afterpay.md
> +Text displayed with the order in your MultiSafepay Control, and on the customer's bank statement (if supported by the bank). Max. 200 characters. HTML is not supported. Use the `items` or `shopping_c
```suggestion
Text displayed with the order in your MultiSafepay Control, and on the customer's bank statement (if supported by the bank). Max. 200 characters. HTML formatting is not supported. To add descriptions in HTML format, use the `items` or `shopping_cart` objects instead.
```

2021-05-25 06:01 UTC, FrancescaNCook commented
Ohhhh I see, not sure how i muddled them (Jira linked tickets probably), but changes only relate to DOCS-2209 not DOCS-1294.

2021-06-10 08:32 UTC, Kris-MultiSafepay approved these changes

2021-06-10 08:35 UTC, merged