DOCS-2223: Add missing brace in AMEX JSON
MultiSafepay/docs pull request #1282
Opened 2021-05-19 06:57 UTC by FrancescaNCook

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2021-05-21 11:11 UTC, Atiq-MultiSafepay requested changes

2021-05-21 11:11 UTC, Atiq-MultiSafepay commented on content/api/payment_methods/post-order-american-express.md
> +    "ip_address": "127.0.0.1" }
@FrancescaNCook I'm not entirely sure if the  } should be after the ip_address. Would be best to check this with Kris.

2021-05-21 11:15 UTC, FrancescaNCook commented on content/api/payment_methods/post-order-american-express.md
> +    "ip_address": "127.0.0.1" }
Ok. I ran both the existing JSON and the fix provided in the ticket through a JSON checking tool and it agreed that the brace was missing. Your thoughts @Kris-MultiSafepay ?

2021-05-24 15:07 UTC, Kris-MultiSafepay commented on content/api/payment_methods/post-order-american-express.md
> +    "ip_address": "127.0.0.1" }
Brace was indeed missing, but should be on a new line (same indentation as line 24). Also, lines 12-22 are indented too far (2 spaces).

2021-05-24 15:08 UTC, Kris-MultiSafepay commented on content/api/payment_methods/post-order-american-express.md
> +    "ip_address": "127.0.0.1" }
```suggestion
    "ip_address": "127.0.0.1"
  }
```

2021-06-01 08:45 UTC, merged