DOCS-2382: Add known errors
MultiSafepay/docs pull request #1335
Opened 2021-06-17 06:20 UTC by FrancescaNCook

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/supported-addresses.md
> +weight: 9
```suggestion
weight: 9
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/changing-order-status-to-shipped.md
> +title : "Changing order status to Shipped"
```suggestion
title : "Changing order status to Shipped"
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/changing-order-status-to-shipped.md
> +meta_title: "Klarna - Changing order status to Shipped - MultiSafepay Docs"
```suggestion
meta_title: "Klarna - Changing order status to Shipped - MultiSafepay Docs"
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/changing-order-status-to-shipped.md
> +weight: 1
```suggestion
weight: 1
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/changing-order-status-to-shipped.md
> +- Automatically using our API, which updates your MultiSafepay Control. Make a PATCH `/orders` request.  See API Reference – [Update an order](https://docs.multisafepay.com/api/#update-an-order).
```suggestion
- Automatically using our API, which updates your MultiSafepay Control. Make a PATCH `/orders` request.  See API Reference – [Update an order](https://docs.multisafepay.com/api/#update-an-order).
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/customizing-invoices.md
> +weight: 4
```suggestion
weight: 4
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/handling-errors.md
> +weight: 10
```suggestion
weight: 10
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/placing-collection-period-on-hold.md
> +weight: 6
```suggestion
weight: 6
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/processing-refunds.md
> +weight: 2
```suggestion
weight: 2
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/processing-refunds.md
> +- You cannot refund more than the amount of the original transaction.
```suggestion
- You cannot refund more than the amount of the original transaction.
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/processing-refunds.md
> +- There is no time limit on refunding successful transactions, so long as the receiving bank can process the refund.
```suggestion
- There is no time limit on refunding successful transactions, so long as the receiving bank can process the refund.
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/processing-refunds.md
> +## Via our API
```suggestion
## Via our API
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/processing-refunds.md
> +Make a POST `/orders/{order_id}/refunds` request. See API Reference – [Refund with shopping cart](/api/#refund-with-shopping-cart).
```suggestion
Make a POST `/orders/{order_id}/refunds` request. See API Reference – [Refund with shopping cart](/api/#refund-with-shopping-cart).
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/reconciliation-and-reports.md
> +weight: 7
```suggestion
weight: 7
```

2021-06-17 06:30 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/reservation-and-invoice-number.md
> +weight: 8
```suggestion
weight: 8
```

2021-06-18 07:29 UTC, Kris-MultiSafepay requested changes
See comment

2021-06-18 07:29 UTC, Kris-MultiSafepay commented on content/payment-methods/billing-suite/klarna/user-guide/handling-errors.md
> +If you receive a `code:BAD_VALUE, Bad value: order_lines[0].reference` error from Klarna, try using shorter SKU numbers (e.g. fewer than 9 characters).
As a merchant, I'd like to know where I would encounter this error and where I can alter the SKU number. 

The error seems to be displayed on the MultiSafepay payment pages, which means that a merchant has to test Klarna payments to see the error (or he/she will find out through customers).

Providing instructions for altering the SKU is a little more tricky as we don't mention SKUs anywhere in our API reference. I suppose that some of the platforms for which we have ecommerce integrations use SKUs, which are provided as values in Klarna order requests. When merchants are building a custom integration, I assume the SKUs would be provided as values for `shopping_cart.items.merchant_item_id`.

2021-06-18 12:00 UTC, FrancescaNCook commented on content/payment-methods/billing-suite/klarna/user-guide/handling-errors.md
> +If you receive a `code:BAD_VALUE, Bad value: order_lines[0].reference` error from Klarna, try using shorter SKU numbers (e.g. fewer than 9 characters).
You're spot on, but I think this is a bit in depth for now. Robert said only one merchant has brought it up and he wasn't even sure it was worth mentioning on Docs. I think the hint is probably enough at the mo?

2021-06-21 10:05 UTC, merged