DOCS-2837: Update PrestaShop page
MultiSafepay/docs pull request #1839
Opened 2021-11-22 15:01 UTC by Joris-MultiSafepay

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2021-11-22 15:17 UTC, Kris-MultiSafepay requested changes

2021-11-22 15:17 UTC, Kris-MultiSafepay commented on content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
> +download_url : "https://github.com/MultiSafepay/prestashop-official/releases/download/5.0.0/Plugin_PrestaShop_5.0.0.zip"
Link is broken. 
```suggestion
download_url : "https://github.com/MultiSafepay/prestashop-official/releases/download/5.0.0-RC2/Plugin_PrestaShop_5.0.0-RC2.zip"
```

2021-11-22 15:17 UTC, Kris-MultiSafepay commented on content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
> +For PrestaShop 1.7.5 or lower, please consider updating PrestaShop or use an older version (4.x) of our plugin which can be found on our [GitHub page](https://github.com/MultiSafepay/prestashop/relea
```suggestion
If you're on PrestaShop 1.7.5 or lower, consider updating PrestaShop or use an older version (4.x) of our plugin which can be found in our [PrestaShop GitHub repository](https://github.com/MultiSafepay/prestashop/releases). 
```

2021-11-22 15:17 UTC, Kris-MultiSafepay commented on content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
> +{{< details title="Upgrading to 5.x from an older version" >}}
```suggestion
{{< details title="Upgrading to version 5.x from an older version" >}}
```

2021-11-22 15:17 UTC, Kris-MultiSafepay commented on content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
> +When updating from an older version of our plugin to the 5.x version, please make sure to keep the older version of the plugin installed until you are sure that all order created with that plugin hav
```suggestion
When you update from an older version of the plugin to 5.x, keep the older version installed until you are sure that orders created with the new plugin are successfully processed.
```

2021-11-22 15:17 UTC, Kris-MultiSafepay commented on content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
> +## Switching to the new plugin
```suggestion
## Switching to the new plugin

```

2021-11-22 15:17 UTC, Kris-MultiSafepay commented on content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
> +1. Go to **Modules** > **Module Manager** > **MultiSafepay** > **Configure**
```suggestion
1. Go to **Modules** > **Module Manager** > **MultiSafepay** > **Configure**.
```

2021-11-22 15:17 UTC, Kris-MultiSafepay commented on content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
> +2. Open the **Payment Methods** tab
```suggestion
2. Open the **Payment Methods** tab.
```

2021-11-22 15:17 UTC, Kris-MultiSafepay commented on content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
> +3. Set all Payment Methods to off
```suggestion
3. Set all Payment Methods to **off**.
```

2021-11-22 15:17 UTC, Kris-MultiSafepay commented on content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
> +4. Open the **Giftcards** tab
```suggestion
4. Open the **Giftcards** tab.
```

2021-11-22 15:17 UTC, Kris-MultiSafepay commented on content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
> +5. Set all Giftcards to off
```suggestion
5. Set all gift cards to **off**.
```

2021-11-22 15:17 UTC, Kris-MultiSafepay commented on content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
> +6. Install and configure the new plugin following the instructions below
```suggestion
6. Install and configure the new plugin following the instructions below.
```

2021-11-22 15:17 UTC, Kris-MultiSafepay commented on content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
> +7. Don't uninstall the older plugin until you are sure all orders created with that plugin have been fully processed
```suggestion
7. Don't uninstall the older plugin until you are sure that orders created with the new plugin are successfully processed 
```

2021-11-22 16:00 UTC, Joris-MultiSafepay commented on content/payments/integrations/ecommerce-platforms/prestashop-1-7/_index.md
> +download_url : "https://github.com/MultiSafepay/prestashop-official/releases/download/5.0.0/Plugin_PrestaShop_5.0.0.zip"
This link was broken, because we were still in the process of releasing. It is now working

2021-11-23 09:16 UTC, Kris-MultiSafepay approved these changes

2021-11-23 09:28 UTC, merged