DOCS-2155: Improve iDEAL QR page
MultiSafepay/docs pull request #1843
Opened 2021-11-23 11:30 UTC by FrancescaNCook

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2021-12-07 21:32 UTC, Kris-MultiSafepay requested changes
Major improvements! Couple of questions and a bit of feedback.

2021-12-07 21:32 UTC, Kris-MultiSafepay commented on content/api/payment_methods/post-order-idealqr.md
> +If you set both `min_amount` and `max_amount` parameters, the `amount` value is ignored.
```suggestion
```

2021-12-07 21:32 UTC, Kris-MultiSafepay commented on content/api/payment_methods/post-order-idealqr.md
> +If you set both `min_amount` and `max_amount` parameters, the `amount` value is ignored.
I just tested this with the amount set to 2000, min_amount set to 1000, and max_amount set to 3000. 

What happened is that I could select any amount to pay from €10 to €30, but the value defaulted to €20. So it's not ignored, however, I'm not sure whether we should state that the value defaults to the `amount` as it's the expected behaviour IMO.

2021-12-07 21:32 UTC, Kris-MultiSafepay commented on content/api/payment_methods/post-order-idealqr.md
> +If `allow_change_amount option` is set to `true`, set the `max_amount`.
```suggestion
If `allow_change_amount` is set to `true`, set the `max_amount`.    
```

2021-12-07 21:32 UTC, Kris-MultiSafepay commented on content/api/payment_methods/post-order-idealqr.md
> +If `min_amount` is not set, the `amount` value is used as the `min_amount` and vice versa.
I don't quite understand this. If min_amount isn't set, the amount value is used as min_amount (tested and true). However what does the vice versa imply? If amount isn't set, the min_amount value is used as amount? (tested and doesn't work/fase). Or is this referring to the max_amount parameter having the same behaviour?

2021-12-07 21:32 UTC, Kris-MultiSafepay commented on content/api/payment_methods/post-order-idealqr.md
> +The `min_amount` must not be more than the `amount`, i.e. `amount` = `max_amount`.
I don't understand what "i.e. `amount` = `max_amount`" means. If `min_amount` is higher than the `amount` the `amount` will be set to the value of `max_amount`? Is the equals sign ('=') assigning or comparing ('==')?

2021-12-07 21:32 UTC, Kris-MultiSafepay commented on content/payments/methods/banks/ideal/_index.md
> +intro_description: "iDEAL is the leading payment method in the Netherlands and links all major Dutch retail banks. Customers can pay online via their own banking environment or mobile app, or offline
How can customers pay offline? The QR code contains a hyperlink that requires an internet connection.

2021-12-07 21:32 UTC, Kris-MultiSafepay commented on content/payments/methods/banks/ideal/_index.md
> +intro_description: "iDEAL is the leading payment method in the Netherlands and links all major Dutch retail banks. Customers can pay online via their own banking environment or mobile app, or offline
Ah okay, I might get it now. Is that supposed to communicate that the QR code itself doesn't require an active internet connection? E.g. the QR code is printed on a sign on top of a mountain and all that's needed for people to pay is a phone with an active internet connection.

2021-12-07 21:32 UTC, Kris-MultiSafepay commented on content/payments/methods/banks/ideal/product-rules.md
> +- You can generate more than one payment link for a single order ID. Subsequent transactions each have a unique order ID.
<img width="931" alt="Screenshot 2021-12-07 at 22 27 37" src="https://user-images.githubusercontent.com/73658536/145108692-2302eefe-9939-4fb3-9086-e7a013fc1fac.png">
What is meant by generating more than one payment link for a single order ID? I can scan a QR code multiple times, but if I try to create a QR code (POST /orders) with the same `order_id`, I get the error above.

2021-12-08 08:04 UTC, FrancescaNCook commented on content/payments/methods/banks/ideal/_index.md
> +intro_description: "iDEAL is the leading payment method in the Netherlands and links all major Dutch retail banks. Customers can pay online via their own banking environment or mobile app, or offline
```suggestion
intro_description: "iDEAL is the leading payment method in the Netherlands and links all major Dutch retail banks. Customers can pay via their own banking environment or mobile app, or by scanning a QR code on a screen or paper. Customers cannot reverse payment and iDEAL guarantees settlement."
```

2021-12-10 09:39 UTC, merged