DOCS-2313: Improve notification URL for ecommerce integrations page
MultiSafepay/docs pull request #1848
Opened 2021-11-25 10:19 UTC by Sarah-MultiSafepay

Hi @FrancescaNCook @Kris-MultiSafepay, please can you test out the preview of this? I'd like you to take the approach of being an external developer that has been hired to build a custom integration for a merchant and you want to know what steps to take to do so.

I'd be interested to hear what changes you notice and general feedback on whether the information provided is suitable in content and structure.

Thanks!

2021-11-25 12:21 UTC, Kris-MultiSafepay requested changes

2021-11-25 12:21 UTC, Kris-MultiSafepay commented on content/getting-started/create-your-integration/build-your-own.md
> +`{your-webhook-endpoint}&transactionid=12345&timestamp=140292929`
```suggestion
`{your-webhook-endpoint}?transactionid=12345&timestamp=140292929`
```

2021-11-25 12:21 UTC, Kris-MultiSafepay commented on content/getting-started/create-your-integration/build-your-own.md
> +`{your-webhook-endpoint}&transactionid=12345&timestamp=140292929`
First query parameter is signified with a `?` unless the webhook endpoint already contains a query parameter (like the testtool).

2021-11-25 12:21 UTC, Kris-MultiSafepay commented on content/getting-started/create-your-integration/build-your-own.md
> +- Have the same [order status](/payments/multisafepay-statuses/).
Why? There might be only an update in the financial status. I think this content originated duplicate notifications (after not successfully acknowledging the receipt).

2021-11-25 12:21 UTC, Kris-MultiSafepay commented on content/getting-started/create-your-integration/build-your-own.md
> +- Don't have the `timestamp` parameter in the URL.
When do notifications not have a timestamp as a query parameter? I believe this is only the case if the notification isn't authentic. If that's the case we can remove this because the timestamp is also mentioned in the next step.

2021-11-25 12:21 UTC, Kris-MultiSafepay commented on content/getting-started/create-your-integration/build-your-own.md
> +Additionally, check whether the timestamp is recent and the originating IP address is MultiSafepay's.
We don't publicize our IP addresses for security reasons (disputable in my opinion since the IP addresses are exposed to everyone communicating with our services). Basically, any merchant can call/mail and ask for our IP addresses for purposes like these (validating authenticity). Should we just clarify that the merchant/developer has to reach out for our IP addresses?

2021-11-25 12:21 UTC, Kris-MultiSafepay commented on content/account/api-onboarding/_index.md
> -- [Notification URL](/developer/api/notification-url)
Maybe change to 'Webhook endpoint' instead?

2021-11-25 12:21 UTC, Kris-MultiSafepay commented on content/developer/api/masking-iban-numbers.md
> +- `POST` notifications
Maybe add a hyperlink? I think in this context the reader might not know what 'POST notifications' refers to.

2021-11-26 08:06 UTC, FrancescaNCook commented on content/account/api-onboarding/add-websites.md
> +For every parameter, we specify whether it's _required_ or _optional_. However, this label refers only to the technical requirements for valid API requests. To process credit card transactions with t
```suggestion
We specify whether each parameter is _required_ or _optional_ for the request to be valid. For example,  to process a credit card payment with a website [API key](/set-up-your-account/site-id-api-key-secure-code), you must provide your expected minimum and maximum order values.
```

2021-11-26 11:18 UTC, FrancescaNCook reviewed
@Sarah-MultiSafepay  See what you think of my suggestions.

2021-11-26 11:18 UTC, FrancescaNCook commented on content/getting-started/create-your-integration/build-your-own.md
> +## Next steps
```suggestion
## Next steps

You've successfully configured your webhook endpoint and web server to handle notifications. For next steps, either view our API reference or test your integration.

{{< two-buttons href-2="/api/" text-2="API reference" description-2="Our comprehensive API reference." img-2="/svgs/API.svg" alt-2="Right arrow" >}}

```

2021-11-26 11:18 UTC, FrancescaNCook commented on content/payments/integrations/ecommerce-platforms/woocommerce/faq/allowing-notifications.md
> +MultiSafepay provides a webhook that is used to receive notifications when there are updates to your orders.
```suggestion
MultiSafepay provides a webhook you can use to receive notifications about updates to your orders.
```

2021-11-26 11:18 UTC, FrancescaNCook commented on content/payments/integrations/ecommerce-platforms/woocommerce/faq/allowing-notifications.md
> +- A refund is processed
```suggestion
The webhook is triggered when the order or transaction status changes, e.g. when:
- A customer completes payment
- A customer's attempt to pay fails 
- You process a refund
```

2021-11-26 11:18 UTC, FrancescaNCook commented on content/payments/integrations/ecommerce-platforms/woocommerce/faq/allowing-notifications.md
> +For more information, see [webhook](/developer/api/webhooks/).
```suggestion
For more information, see [Webhooks](/developer/api/webhooks/).
```

2021-11-26 11:18 UTC, FrancescaNCook commented on content/developer/api/webhooks.md
> +meta_title: "Webhooks - MultiSafepay Docs"
```suggestion
title : "Notification webhook"
meta_title: "Notification webhook - MultiSafepay Docs"
```

2021-11-26 11:18 UTC, FrancescaNCook commented on content/developer/api/webhooks.md
> +meta_title: "Webhooks - MultiSafepay Docs"
This page is about only 1 webhook, so I think we should name it specifically.

2021-11-29 12:59 UTC, Sarah-MultiSafepay commented on content/getting-started/create-your-integration/build-your-own.md
> +- Have the same [order status](/payments/multisafepay-statuses/).
We discussed the reasons why these are here.

2021-11-29 12:59 UTC, Sarah-MultiSafepay commented on content/getting-started/create-your-integration/build-your-own.md
> +- Don't have the `timestamp` parameter in the URL.
There are other scenarios, as discussed.

2021-11-29 13:05 UTC, Sarah-MultiSafepay commented on content/getting-started/create-your-integration/build-your-own.md
> +Additionally, check whether the timestamp is recent and the originating IP address is MultiSafepay's.
Good idea. I've added a note for the reader to contact the Integrations team for a list of MultiSafepay IP addresses.

2021-11-29 13:12 UTC, Sarah-MultiSafepay commented on content/account/api-onboarding/_index.md
> -- [Notification URL](/developer/api/notification-url)
I thought it would be better to have it removed as it's only optional to be set. The only time this is really useful is when a manual payment link is generated. I discussed with Jasper and he agreed to just remove it for now and we'll monitor the situation for the next two months.

2021-11-29 13:14 UTC, Sarah-MultiSafepay commented on content/developer/api/masking-iban-numbers.md
> +- `POST` notifications
Added a link to the webhooks knowledge article.

2021-11-29 13:27 UTC, Sarah-MultiSafepay commented on content/getting-started/create-your-integration/build-your-own.md
> +If you leave the `notification_url` parameter empty in the API request then the **Notification URL** set in your [MultiSafepay account](https://merchant.multisafepay.com) is used.
I had to change this sentence as the website settings actually overwrite the API settings.

2021-11-29 13:40 UTC, Sarah-MultiSafepay commented on content/account/api-onboarding/add-websites.md
> +For every parameter, we specify whether it's _required_ or _optional_. However, this label refers only to the technical requirements for valid API requests. To process credit card transactions with t
Agreed. I've removed the paragraph.

2021-11-30 12:54 UTC, closed without merging

2021-12-08 16:24 UTC, Sarah-MultiSafepay commented on content/getting-started/create-your-integration/build-your-own.md
> +meta_title: "Getting Started - Build your own integration - MultiSafepay Docs"
@FrancescaNCook, "configuring the notification webhook" sounds a bit strange to me. Would "Configuring your webhook endpoint" work as an alternative? I think it is more technically accurate.