DOCS-2313: Improve notification URL for ecommerce integrations page (continued)
MultiSafepay/docs pull request #1862
Opened 2021-11-30 14:36 UTC by Sarah-MultiSafepay

This is a continuation of https://github.com/MultiSafepay/docs/pull/1848 

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2021-12-09 09:20 UTC, Sarah-MultiSafepay commented
Hi @Kris-MultiSafepay, can you review my new version of the tutorial?

2021-12-12 12:09 UTC, Kris-MultiSafepay requested changes
Great progress

2021-12-12 12:09 UTC, Kris-MultiSafepay commented on content/payments/integrations/build-your-own/configure-your-webhook.md
> +
Again, we could add a sentence here to **emphasize the success** of this step and **connects it to the next steps** e.g. "Now that you've [...], let's [...]".

2021-12-12 12:09 UTC, Kris-MultiSafepay commented on content/payments/integrations/build-your-own/handle-notifications.md
> +- `transactionid`: Your unique identifier for the order
Because the name suggests otherwise, I think it's important to stress that the `transactionid` is actually the client-defined `order_id`

2021-12-12 12:09 UTC, Kris-MultiSafepay commented on content/payments/integrations/build-your-own/handle-notifications.md
> +We add the current order details to the request body.
```suggestion
The updated order details make up the payload of the request.
```

2021-12-12 12:09 UTC, Kris-MultiSafepay commented on content/payments/integrations/build-your-own/next-steps.md
> +For next steps, either review our API reference documentation to see what else you can do with our API:
I think it's worthwhile for us to discuss what directions we should be pointing to the user after this tutorial. Options include:

- Swapping our the API-only integration for a Payment Component for embedded payments
- Adding Second Chance functionality to optimize conversion
etc.

I think it's worth stressing _why_ our users would want to perform the next step, depending on their type of integration.

2021-12-13 14:51 UTC, Sarah-MultiSafepay commented on content/payments/integrations/build-your-own/_index.md
> +This page provides an overview of building your own integration.
@Kris-MultiSafepay, what about: "This tutorial takes you through the key steps to build your own integration successfully."

2021-12-13 15:25 UTC, Sarah-MultiSafepay commented on content/payments/integrations/build-your-own/configure-your-webhook.md
> +  "payment_options": {
@Kris-MultiSafepay, I'd like to try and keep this tutorial as lean as possible. Maybe we could consider a tutorial which gives further details on what options there are in the API reference to further customise their integration? So redirect_url, cancel_url, close_window, the check_out options object, settings object.

Alternatively, there could be another section in this tutorial just for the redirect and cancel_url in this tutorial.

2021-12-13 15:54 UTC, Sarah-MultiSafepay commented on content/payments/integrations/build-your-own/configure-your-webhook.md
> +### Website level
Agreed.

2022-01-03 14:51 UTC, Sarah-MultiSafepay commented on content/payments/integrations/build-your-own/manage-orders.md
> +The most common operation to perform with our API is to create an order. There are two types of orders: direct or redirect. Depending which type you select, affects which payment flow the customer ex
I've worked around this by changing the wording to refer to the `type` attribute.

2022-01-11 15:26 UTC, Sarah-MultiSafepay commented on content/payments/integrations/build-your-own/next-steps.md
> +For next steps, either review our API reference documentation to see what else you can do with our API:
Hi @Kris-MultiSafepay,
I asked Tarick for his view on this and updated the next steps with his suggestions. Let me know what you think!

2022-01-12 10:28 UTC, Kris-MultiSafepay approved these changes

2022-01-12 10:28 UTC, Kris-MultiSafepay commented on content/developer/api/webhooks.md
> +The webhook is triggered when the [order or transaction status](/payments/multisafepay-statuses/) changes, e.g. when:
```suggestion
The webhook is triggered when the [order or transaction status](/payments/multisafepay-statuses/) changes, e.g. when:

```

2022-01-12 10:28 UTC, Kris-MultiSafepay commented on content/developer/api/webhooks.md
> +The webhook is triggered when the [order or transaction status](/payments/multisafepay-statuses/) changes, e.g. when:
Sometimes Hugo fails to correctly compile an unordered list without a leading empty line

2022-01-12 10:28 UTC, Kris-MultiSafepay commented on content/developer/api/webhooks.md
> +If you are building your own integration, you need to configure this yourself. See - [Configure your webhook endpoint](/integrations/build-your-own/configure-your-webhook/).
check all links to the tutorial after changing its hyperlinks to /integrations/self-made/[...]

2022-01-12 10:28 UTC, Kris-MultiSafepay commented on content/integration/build-your-own/configure-your-webhook.md
> +To use this webhook, you need to set a webhook endpoint. The webhook endpoint must be a URL that:
```suggestion
To use this webhook, you need to set a webhook endpoint. The webhook endpoint must be a URL that:

```

2022-01-12 10:28 UTC, Kris-MultiSafepay commented on content/integration/build-your-own/handle-notifications.md
> +If for some reason you don't receive a notification:
```suggestion
If for some reason you don't receive a notification:

```

2022-01-12 10:28 UTC, Kris-MultiSafepay commented on content/integration/build-your-own/manage-orders.md
> +Before making any API requests you must:
```suggestion
Before making any API requests you must:

```

2022-01-12 10:28 UTC, Kris-MultiSafepay commented on content/integration/build-your-own/validate-hmac-signatures.md
> +3. Concatenate the:
```suggestion
3. Concatenate the:

```

2022-01-13 10:40 UTC, FrancescaNCook submitted a review, later dismissed
Great work! Mostly minor comma-y changes.

2022-01-13 10:40 UTC, FrancescaNCook commented on content/integration/self-made/manage-orders.md
> +Whilst building your integration we recommend using the test environment: `https://testapi.multisafepay.com/v1/json`.
"Whilst" is a bit antiquated for most non-native speakers.

2022-01-13 10:40 UTC, FrancescaNCook commented on content/integration/self-made/manage-orders.md
> +To familiarize yourself with what an order looks like in our system, try making a `GET` request for your [order details](/api/#get-order-details) with the `order_id` from the order you just created.
```suggestion
To familiarize yourself with what an order looks like in our system, try making a [`GET` order details request](/api/#get-order-details) for the order you just created, using the `order_id`.
```

2022-01-13 10:40 UTC, FrancescaNCook commented on content/integration/self-made/manage-orders.md
> +The second most important parameter is `financial_status` which represents the [status of the transaction](/payments/multisafepay-statuses/) and shows the progression towards settling the funds in yo
```suggestion
The second most important parameter is `financial_status`, which represents the [status of the transaction](/payments/multisafepay-statuses/), i.e. the progression towards settling the funds in your MultiSafepay balance.
```

2022-01-13 10:40 UTC, FrancescaNCook commented on content/integration/self-made/manage-orders.md
> +In this example, the `status` is `completed`. This means that the customer has completed payment and settlement is guaranteed. The `financial_status` is also `completed`. This means that the funds ha
```suggestion
In this example, the `status` is **Completed**. This means that the customer has completed payment and settlement is guaranteed. The `financial_status` is also **Completed**. This means that the funds have been settled in your MultiSafepay balance.
```

2022-01-13 10:40 UTC, FrancescaNCook commented on content/integration/self-made/manage-orders.md
> +Now that you know how to create an order, check its details, and know what is important to look for, it's the perfect time to introduce you to our webhook.
```suggestion
Now that you know how to create an order and check its details, and what is important to look for, it's the perfect time to introduce you to our webhook.
```

2022-01-13 10:40 UTC, FrancescaNCook commented on content/integration/self-made/manage-orders.md
> +Now that you know how to create an order, check its details, and know what is important to look for, it's the perfect time to introduce you to our webhook.
Great tone you're using here. Accessible, friendly, but not cringey.

2022-01-13 10:40 UTC, FrancescaNCook commented on content/integration/self-made/manage-orders.md
> +So that you don't have to continually poll our server to see if there is an update to your order, we provide a webhook to send you notifications automatically. In the next section we explain what you
```suggestion
So that you don't have to continually poll our server to see if there are updates to your orders, we provide a webhook to send you notifications automatically. In the next section we explain what you need to do to configure this to work with your web server.
```

2022-01-13 10:40 UTC, FrancescaNCook commented on content/integration/self-made/next-steps.md
> +short_description: 'Build your own payments integration with our API, wrappers or SDKs'
```suggestion
short_description: 'Build your own payments integration with our API, wrappers, or SDKs.'
```

2022-01-13 10:40 UTC, FrancescaNCook commented on content/integration/self-made/next-steps.md
> +Congratulations! You've successfully created an order, configured your webhook endpoint and set up your web server to handle notifications.
```suggestion
Congratulations! You've successfully created an order, configured your webhook endpoint, and set up your web server to handle notifications. 
```

2022-01-13 10:40 UTC, FrancescaNCook commented on content/integration/self-made/validate-hmac-signatures.md
> +short_description: 'Validate HMAC signatures of notifications'
```suggestion
short_description: 'Validate HMAC signatures of notifications.'
```

2022-01-13 10:40 UTC, FrancescaNCook commented on content/integration/self-made/validate-hmac-signatures.md
> +To validate the HMAC signature of a `POST` notification request in your own solution, follow these steps:
```suggestion
To validate the HMAC signature of `POST` notification requests in your self-made integration, follow these steps:
```

2022-01-13 10:40 UTC, FrancescaNCook commented on content/integration/self-made/validate-hmac-signatures.md
> +    Additionally, check whether the timestamp is recent and the originating IP address is MultiSafepay's. For a list of MultiSafepay's IP addresses, contact <integration@multisafepay.com>
```suggestion
    Additionally, check whether the timestamp is recent and the originating IP address is MultiSafepay's. For a list of MultiSafepay IP addresses, email the Integration Team at <integration@multisafepay.com>
```

2022-01-13 10:40 UTC, FrancescaNCook commented on content/payments/methods/credit-and-debit-cards/american-express/_index.md
> +url: '/payments-methods/american-express/'
```suggestion
url: '/payment-methods/american-express/'
```

2022-01-13 10:40 UTC, FrancescaNCook commented on content/payments/methods/credit-and-debit-cards/cartes-bancaires/_index.md
> +url: '/payments-methods/cartes-bancaires/'
```suggestion
url: '/payment-methods/cartes-bancaires/'
```

2022-02-23 14:54 UTC, FrancescaNCook submitted a review, later dismissed

2022-02-23 15:41 UTC, merged