Docs 2979
MultiSafepay/docs pull request #2023
Opened 2022-03-03 08:15 UTC by FrancescaNCook

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2022-03-03 10:40 UTC, Sarah-MultiSafepay requested changes

2022-03-03 10:40 UTC, Sarah-MultiSafepay commented on content/payments/methods/credit-and-debit-cards/american-express/overview.md
> +url: '/payment-methods/amex/overview/'
The main URL is still: /payment-methods/american-express/
Should we change it to amex?
And the activation page is: /payment-methods/american-express/activation/ which doesn't match the rest.

2022-03-07 08:06 UTC, FrancescaNCook commented on content/payments/methods/credit-and-debit-cards/american-express/overview.md
> +url: '/payment-methods/amex/overview/'
Good spotting! Fixed.

2022-03-07 08:15 UTC, FrancescaNCook commented on content/payments/methods/credit-and-debit-cards/mastercard/_index.md
> +    - /payments/methods/credit-and-debit-cards/mastercard/
@Sarah-MultiSafepay  Not quite sure I understand your comment, sorry? The alias in your-logo-online-banking.md is part of a much longer former URL: /payments/methods/credit-and-debit-cards/mastercard/user-guide/displaying-your-logo-in-online-banking/ ?

2022-03-08 08:29 UTC, Sarah-MultiSafepay commented on content/payments/methods/credit-and-debit-cards/mastercard/_index.md
> +    - /payments/methods/credit-and-debit-cards/mastercard/
@FrancescaNCook, not sure anymore! Looks fine now though.

2022-03-08 08:49 UTC, Sarah-MultiSafepay requested changes
A few suggested changes!
Could you also: 
- Fix `/developer/api/difference-between-direct-and-redirect` in `payment_methods.md`
- Change ZilverCMS contact URL in `zilvercms/index.md` to `https://www.zilverhq.nl/contact`

2022-03-08 08:49 UTC, Sarah-MultiSafepay commented on content/api/reference/customer-object.md
> +Required for [pay later methods](/payments/methods/pay-later/) and [credit cards](/payment-methods/credit-debit-cards/) as part of our [fraud check](/glossaries/credit-cards/#uncleared-transactions),
```suggestion
Required for [pay later methods](/payment-methods/pay-later/) and [credit cards](/payment-methods/credit-debit-cards/) as part of our [fraud check](/glossaries/credit-cards/#uncleared-transactions), optional but recommended for other payment methods.  
```

2022-03-08 08:49 UTC, Sarah-MultiSafepay commented on content/getting-started/glossary/multisafepay-glossary.md
> +Software merchants use to sell products and services and accept payments, e.g website, mobile app, [PWA](/payments/integrations/pwa/). Merchants may use [ecommerce platforms](/integrations/ready-made
```suggestion
Software merchants use to sell products and services and accept payments, e.g website, mobile app, [PWA](/payments/integrations/pwa/). Merchants may use [ecommerce platforms](/integrations/ready-made/) or [build their own integration](/integrations/self-made/).
```

2022-03-08 08:49 UTC, Sarah-MultiSafepay commented on content/my-account/manage-account/managing-your-balance.md
> +You can set your daily balance report to include the balance of uncleared transactions. This is particularly useful if you offer [pay later](/payments/methods/pay-later/) and/or [credit card](/paymen
```suggestion
You can set your daily balance report to include the balance of uncleared transactions. This is particularly useful if you offer [pay later](/payment-methods/pay-later/) and/or [credit card](/payment-methods/credit-debit-cards/) payment methods. 
```

2022-03-08 08:49 UTC, Sarah-MultiSafepay commented on content/payments/features/recurring-payments/_index.md
> +- [Woocommerce](/woocommerce/)
```suggestion
- [Magento 1](/magento-1)
- [Magento 2](/magento-2)
- [PrestaShop 1.6](/prestashop-1-6)
- [PrestaShop 1.7](/prestashop)
- [Shopware 6](/shopware-6) 
- [Woocommerce](/woo-commerce/) 
```

2022-03-08 09:16 UTC, merged