DOCS-3301: Change paths of logos to absolute
MultiSafepay/docs pull request #2136
Opened 2022-05-25 14:08 UTC by Kris-MultiSafepay

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2022-05-25 14:39 UTC, Sarah-MultiSafepay requested changes

2022-05-25 14:39 UTC, Sarah-MultiSafepay commented on content/accounting/integrations/Exact/integrations/xcore.md
> +logo: 'https://raw.githubusercontent.com/MultiSafepay/docs/master/static/logo/accounting/xcore.png'
Can you double quote this and all the other URLs listed in the logo parameter? The single quote messes with the markdown link checker.

2022-05-27 07:37 UTC, Kris-MultiSafepay commented on content/accounting/integrations/Exact/integrations/xcore.md
> +logo: 'https://raw.githubusercontent.com/MultiSafepay/docs/master/static/logo/accounting/xcore.png'
Sure thing!

2022-05-30 09:01 UTC, Sarah-MultiSafepay reviewed
There are a few places where I'm not sure we should change from single quotes to double quotes. E.g. in code excerpts. And if you really want to go all the way, you should review `meta_title` and `short_description`. :grinning:

2022-06-01 09:10 UTC, Kris-MultiSafepay commented on content/integration/checkouts/payment-components/previous-release/previous-release-2.md
> +    env: "test",
```suggestion
    env: 'test',
```

2022-06-01 09:44 UTC, merged