DOCS-3292: import developers
MultiSafepay/docs pull request #2155
Opened 2022-06-01 07:58 UTC by Sarah-MultiSafepay

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2022-06-01 08:59 UTC, FrancescaNCook approved these changes
Sorry, slipped in a quick tech edit. Don't think I've ever looked at these pages!

2022-06-01 08:59 UTC, FrancescaNCook commented on content/developer/wrappers-and-sdks.md
> +[View it on GitHub](https://github.com/MultiSafepay/php-sdk)
```suggestion
[View on GitHub](https://github.com/MultiSafepay/php-sdk).
```

2022-06-01 08:59 UTC, FrancescaNCook commented on content/developer/wrappers-and-sdks.md
> +A Laravel wrapper which wraps the MultiSafepay PHP SDK.
```suggestion
A Laravel wrapper for MultiSafepay's PHP SDK.
```

2022-06-01 08:59 UTC, FrancescaNCook commented on content/developer/wrappers-and-sdks.md
> +[View it on GitHub](https://github.com/MultiSafepay/laravel-api)
```suggestion
[View on GitHub](https://github.com/MultiSafepay/laravel-api).
```

2022-06-01 08:59 UTC, FrancescaNCook commented on content/developer/wrappers-and-sdks.md
> +A wrapper for Python to easily use the MultiSafepay API in your Python projects.
```suggestion
The Python wrapper for MultiSafepay's REST API.
```

2022-06-01 08:59 UTC, FrancescaNCook commented on content/developer/wrappers-and-sdks.md
> +[View it on GitHub](https://github.com/MultiSafepay/multisafepay-python-wrapper)
```suggestion
[View on GitHub](https://github.com/MultiSafepay/multisafepay-python-wrapper).
```

2022-06-01 08:59 UTC, FrancescaNCook commented on content/developer/wrappers-and-sdks.md
> +[View it on GitHub](https://github.com/MultiSafepay/.Net)
```suggestion
[View on GitHub](https://github.com/MultiSafepay/.Net).
```

2022-06-01 08:59 UTC, FrancescaNCook commented on content/developer/wrappers-and-sdks.md
> +[View it on GitHub](https://github.com/edoburu/django-multisafepay)
```suggestion
[View on GitHub](https://github.com/edoburu/django-multisafepay).
```

2022-06-01 08:59 UTC, FrancescaNCook commented on content/developer/wrappers-and-sdks.md
> +Go wrapper for the MultiSafepay API developed by kurt-stolle.
```suggestion
GO wrapper for MultiSafepay's REST API developed by kurt-stolle.
```

2022-06-01 08:59 UTC, FrancescaNCook commented on content/developer/wrappers-and-sdks.md
> +[View it on GitHub](https://github.com/kurt-stolle/go-multisafepay)
```suggestion
[View on GitHub](https://github.com/kurt-stolle/go-multisafepay).
```

2022-06-02 11:13 UTC, Kris-MultiSafepay requested changes

2022-06-02 11:13 UTC, Kris-MultiSafepay commented on content/developer/fastcheckout-android-sdk.md
> +<img src="https://raw.githubusercontent.com/MultiSafepay/docs/1281f9320696f2d256d0859421ec2cfa2350e644/static/logo/Integrations/Fastcheckout_Android.svg" width="100" align ="right"/>
```suggestion
<img src="https://raw.githubusercontent.com/MultiSafepay/docs/master/static/logo/Integrations/Fastcheckout_Android.svg" width="100" align ="right"/>
```

2022-06-02 11:13 UTC, Kris-MultiSafepay commented on content/developer/fastcheckout-ios-sdk.md
> +<img src="https://raw.githubusercontent.com/MultiSafepay/docs/1281f9320696f2d256d0859421ec2cfa2350e644/static/logo/Integrations/Fastcheckout_iOS.svg" width="100" align ="right"/>
```suggestion
<img src="https://raw.githubusercontent.com/MultiSafepay/docs/master/static/logo/Integrations/Fastcheckout_iOS.svg" width="100" align ="right"/>
```

2022-06-02 11:13 UTC, Kris-MultiSafepay commented on content/developer/fastcheckout-ios-sdk.md
>  As an integrator, you only need to provide a valid MSP transaction identifier or create a transaction. The FastCheckout SDK leverages the checkout process for you, providing notifications for all pos
Isn't this duplicating line 8?

2022-06-02 11:13 UTC, Kris-MultiSafepay commented on content/developer/wrappers-and-sdks.md
> +<img src="https://raw.githubusercontent.com/MultiSafepay/docs/1281f9320696f2d256d0859421ec2cfa2350e644/static/logo/Integrations/PHP.svg" width="100" align ="right"/>
```suggestion
<img src="https://raw.githubusercontent.com/MultiSafepay/docs/master/static/logo/Integrations/PHP.svg" width="100" align ="right"/>
```

2022-06-02 11:13 UTC, Kris-MultiSafepay commented on content/developer/wrappers-and-sdks.md
> +<img src="https://raw.githubusercontent.com/MultiSafepay/docs/1281f9320696f2d256d0859421ec2cfa2350e644/static/logo/Integrations/Laravel.svg" width="100" align ="right"/>
```suggestion
<img src="https://raw.githubusercontent.com/MultiSafepay/docs/master/static/logo/Integrations/Laravel.svg" width="100" align ="right"/>
```

2022-06-02 11:13 UTC, Kris-MultiSafepay commented on content/developer/wrappers-and-sdks.md
> +<img src="https://raw.githubusercontent.com/MultiSafepay/docs/1281f9320696f2d256d0859421ec2cfa2350e644/static/logo/Integrations/Java.svg" width="100" align ="right"/>
```suggestion
<img src="https://raw.githubusercontent.com/MultiSafepay/docs/master/static/logo/Integrations/Java.svg" width="100" align ="right"/>
```

2022-06-02 11:13 UTC, Kris-MultiSafepay commented on content/developer/wrappers-and-sdks.md
> +<img src="https://raw.githubusercontent.com/MultiSafepay/docs/1281f9320696f2d256d0859421ec2cfa2350e644/static/logo/Integrations/NodeJS.svg" width="100" align ="right"/>
```suggestion
<img src="https://raw.githubusercontent.com/MultiSafepay/docs/master/static/logo/Integrations/NodeJS.svg" width="100" align ="right"/>
```

2022-06-02 11:13 UTC, Kris-MultiSafepay commented on content/developer/wrappers-and-sdks.md
> +<img src="https://raw.githubusercontent.com/MultiSafepay/docs/1281f9320696f2d256d0859421ec2cfa2350e644/static/logo/Integrations/Python.svg" width="100" align ="right"/>
```suggestion
<img src="https://raw.githubusercontent.com/MultiSafepay/docs/master/static/logo/Integrations/Python.svg" width="100" align ="right"/>
```

2022-06-02 11:13 UTC, Kris-MultiSafepay commented on content/developer/wrappers-and-sdks.md
> +## .Net
```suggestion
## .NET
```

2022-06-02 11:13 UTC, Kris-MultiSafepay commented on content/developer/wrappers-and-sdks.md
> +The .Net wrapper for MultiSafepay's payments API, which supports all payment methods.
```suggestion
The .NET wrapper for MultiSafepay's payments API, which supports all payment methods.
```

2022-06-02 11:13 UTC, Kris-MultiSafepay commented on content/developer/wrappers-and-sdks.md
> +The Node wrapper for MultiSafepay's REST API.
```suggestion
The Node.js wrapper for MultiSafepay's REST API.
```

2022-06-02 11:35 UTC, Sarah-MultiSafepay commented on content/developer/fastcheckout-ios-sdk.md
>  As an integrator, you only need to provide a valid MSP transaction identifier or create a transaction. The FastCheckout SDK leverages the checkout process for you, providing notifications for all pos
This is resolved in Francesca's tech edit!

2022-06-02 11:41 UTC, Kris-MultiSafepay approved these changes

2022-06-02 11:59 UTC, merged