DOCS-3613: Document Exact Online automated integration
MultiSafepay/docs pull request #2474
Opened 2022-09-08 06:52 UTC by FrancescaNCook

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2022-09-12 11:37 UTC, Sarah-MultiSafepay commented on content/accounting/accounting-integrations.md
> +<details id="how-to-automate-exports-to-exact-online">
```suggestion
<details id="how-to-automate-exports-with-exact-online">
```

2022-09-12 11:37 UTC, Sarah-MultiSafepay commented on content/accounting/accounting-integrations.md
> +   1. Sign in to your <a href="https://merchant.multisafepay.com" target="_blank">MultiSafepay dashboard</a> <i class="fa fa-external-link" style="font-size:12px;color:#8b929e"></i>.
Should we use roman numerals to help differentiate between the two numbering sets?

2022-09-12 11:37 UTC, Sarah-MultiSafepay commented on content/accounting/accounting-integrations.md
> +       - From the **Type** list, select the type: **90 "General"** for all except **MultiSafepayImportedRows**, which is **12 "Bank"**).
```suggestion
       - From the **Type** list, select the type: **90 "General"** for all except **MultiSafepayImportedRows**, which is **12 "Bank"**.
```

2022-09-12 11:37 UTC, Sarah-MultiSafepay commented on content/accounting/accounting-integrations.md
> +---
```suggestion
---

```

2022-09-12 11:37 UTC, Sarah-MultiSafepay commented on content/accounting/accounting-integrations.md
> +---
```suggestion
---

```

2022-09-12 11:37 UTC, Sarah-MultiSafepay commented on content/accounting/accounting-integrations.md
> +---
```suggestion
---

```

2022-09-12 11:37 UTC, Sarah-MultiSafepay commented on content/accounting/accounting-integrations.md
> +---
```suggestion
---

```

2022-09-12 11:37 UTC, Sarah-MultiSafepay commented on content/accounting/accounting-integrations.md
> +---
```suggestion
---

```

2022-09-12 11:37 UTC, Sarah-MultiSafepay commented on content/accounting/accounting-integrations.md
> +---
```suggestion
---

```

2022-09-12 11:37 UTC, Sarah-MultiSafepay commented on content/accounting/accounting-integrations.md
> +---
```suggestion
---

```

2022-09-12 11:49 UTC, FrancescaNCook commented on content/accounting/accounting-integrations.md
> +   1. Sign in to your <a href="https://merchant.multisafepay.com" target="_blank">MultiSafepay dashboard</a> <i class="fa fa-external-link" style="font-size:12px;color:#8b929e"></i>.
@Sarah-MultiSafepay Readme does that automatically, but I'm happy to make the markdown match.

2022-09-12 11:54 UTC, FrancescaNCook commented on content/accounting/accounting-integrations.md
> +   1. Sign in to your <a href="https://merchant.multisafepay.com" target="_blank">MultiSafepay dashboard</a> <i class="fa fa-external-link" style="font-size:12px;color:#8b929e"></i>.
Hmm, the markdown doesn't seem to like it. I think I'll leave it as is in the backend. It renders nicely in Readme.

2022-09-15 10:07 UTC, Sarah-MultiSafepay approved these changes

2022-09-15 10:56 UTC, Sarah-MultiSafepay commented on wordlist.txt
> +favicon
```suggestion
favicon
MultiSafepayImportedRows
```

2022-12-22 10:59 UTC, Rendani-MultiSafepay approved these changes

2023-02-21 14:55 UTC, inesmayerMSP requested changes

2023-02-21 14:55 UTC, inesmayerMSP commented on content/accounting/accounting-integrations.md
> +    You are redirected to your MultiSafepay dashboard. This make take a few seconds while MultiSafepay creates ledger accounts for you.
may take

2023-02-21 14:55 UTC, inesmayerMSP commented on content/accounting/accounting-integrations.md
> +4. Grant MultiSafepay access to Exact Online only or to Exact Online and future companies.
further?

2023-02-21 14:55 UTC, inesmayerMSP commented on content/accounting/accounting-integrations.md
> +❗️If you rename, modify, or delete information in Exact Online, exports will fail. If you get an error, email <support@multisafepay.com>
If you encounter

2023-02-21 14:55 UTC, inesmayerMSP commented on content/accounting/accounting-integrations.md
> +❗️If you rename, modify, or delete information in Exact Online, exports will fail. If you get an error, email <support@multisafepay.com>
space after excl point

2023-03-20 11:53 UTC, inesmayerMSP requested changes

2023-03-20 11:53 UTC, inesmayerMSP commented on content/accounting/accounting-integrations.md
> +❗️If you delete, or modify information in Exact Online, exports will fail. If you get an error, email <support@multisafepay.com>
if you delete or modify; If you encounter an error

2023-03-20 11:53 UTC, inesmayerMSP commented on content/accounting/accounting-integrations.md
> +4. Under **Financial years** page > click on **New** >  **Create** <br> Create new financial year pop-up screen appears.
needs to be coherent: Under xxxx page / under the xxx page / under xxx

2023-03-20 11:53 UTC, inesmayerMSP commented on content/accounting/accounting-integrations.md
> +❗️If you delete, or modify information in Exact Online, exports will fail. If you get an error, email <support@multisafepay.com>
if you delete or modify; if you encounter an error,

2023-03-20 21:15 UTC, merged