DOCS-3781: Document PayPal automatic onboarding
MultiSafepay/docs pull request #2659
Opened 2023-01-19 15:41 UTC by Rendani-MultiSafepay

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2023-03-10 12:43 UTC, inesmayerMSP requested changes

2023-03-10 12:43 UTC, inesmayerMSP commented on content/payment-methods/paypal.md
> +3. In the **PayPal  tab** > click on **Set up PayPal** button <br>                                                                                                      You are redirected to sign in t
tab not bold

2023-03-10 12:43 UTC, inesmayerMSP commented on content/payment-methods/paypal.md
> +3. In the **PayPal  tab** > click on **Set up PayPal** button <br>                                                                                                      You are redirected to sign in t
You are redirected to PayPal to sign in to your Paypal business account

2023-03-10 12:43 UTC, inesmayerMSP commented on content/payment-methods/paypal.md
> +**Note**: For disputes and disbursement information, further details appears in a transaction note  in your dashboard under  **Transaction overview** > **Transaction summary**.
further details appear

2023-03-13 10:28 UTC, rossthomasmsp approved these changes

2023-03-13 10:31 UTC, merged