DOCS-3816: Remove Google analytics
MultiSafepay/docs pull request #2667
Opened 2023-02-07 14:49 UTC by Rendani-MultiSafepay

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2023-02-09 14:19 UTC, Daniel-MultiSafepay submitted a review, later dismissed

2023-02-09 15:33 UTC, rossthomasmsp approved these changes

2023-02-09 15:45 UTC, Daniel-MultiSafepay requested changes
Hi @Rendani-MultiSafepay . 

Inject the tracking code into the payment page is not supported anymore.  However there are still remnants of this information in this page, and not removed in this PR: 

https://docs.multisafepay.com/docs/google-analytics

Look for: 

"You can add your tracking ID or tag in your integration by adding it in google_analytics.account when you [create an order] (https://docs.multisafepay.com/reference/createorder/)."

Once you remove that part, it seems to me there are no other paragraph saying the Google Analytics tracking ID could be used in the payment page.  

But...  Why are we talking about Google Analytics in our documentation, if this is not longer supported.  IMHO, I think the whole page needs to be removed.

2023-03-16 12:04 UTC, rossthomasmsp approved these changes

2023-03-16 12:25 UTC, merged