PLGVIR4-20: Draft about the technical manual for VirtueMart 4.x
MultiSafepay/docs pull request #2669
Opened 2023-02-15 11:27 UTC by Miguel-MultiSafepay

Draft to add the new documentation for VirtueMart 4, including the renaming of the previous version (from VirtueMart to VirtueMart 3).

To try to speed up the process, I have renamed wherever VirtueMart was present to VirtueMart 3 adding VirtueMart 4 at the same time.

This PR is also a Draft so we can solve any possible wrong renaming or to add or to change any other point.

2023-02-21 09:05 UTC, Daniel-MultiSafepay commented on content/integrations/virtuemart-3.md
> +slug: 'virtuemart 3'
A slug should not contain white spaces. The URL of this page will be defined by this value.

2023-02-21 09:07 UTC, Daniel-MultiSafepay commented on content/integrations/virtuemart-4.md
> +order: 18
I think the "order" property needs to be redefined in all pages with the same parent to open a space for this one.  At this moment this is the same one defined in virtuemart-3 page. Please @Miguel-MultiSafepay, check this with @Rendani-MultiSafepay to receive instructions about how this should be done.

2023-02-21 09:22 UTC, Daniel-MultiSafepay commented on content/integrations/virtuemart-4.md
> +- <<glossary:BNPL>>: All
This line needs to be removed, because we are not building and passing the shopping cart object within the order request in this integration. For the same reason is not possible create transactions using BNPL methods.

2023-02-21 09:23 UTC, Daniel-MultiSafepay requested changes
Please @Miguel-MultiSafepay, check previously submitted inline comments.

2023-02-21 11:31 UTC, Miguel-MultiSafepay commented on content/integrations/virtuemart-4.md
> +- <<glossary:BNPL>>: All
I removed the line referring to "buy now pay later methods", namely <<glossary:BNPL>>: All

2023-02-21 11:32 UTC, Miguel-MultiSafepay commented on content/integrations/virtuemart-4.md
> +order: 18
Ok I will speak with Rendani

2023-02-21 11:38 UTC, Miguel-MultiSafepay commented on content/integrations/virtuemart-3.md
> +slug: 'virtuemart 3'
OK, understood. I have changed the blank space with an hyphen

2023-03-30 07:44 UTC, Rendani-MultiSafepay requested changes

2023-03-30 08:12 UTC, Miguel-MultiSafepay commented on content/integrations/virtuemart-4.md
> +- Joomla 4.x + VirtueMart 4.x
Done!!

2023-03-30 09:58 UTC, merged