DOCS-3796: Update payment components and tokenization
MultiSafepay/docs pull request #2674
Opened 2023-02-22 11:42 UTC by Rendani-MultiSafepay

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2023-03-02 10:09 UTC, Daniel-MultiSafepay approved these changes

2023-03-14 14:24 UTC, inesmayerMSP requested changes

2023-03-14 14:24 UTC, inesmayerMSP commented on content/integrations/prestashop-1-6.md
> +- Cards: Amex, Maestro, Mastercard, and Visa.
no full stop

2023-03-14 14:24 UTC, inesmayerMSP commented on content/integrations/prestashop-1-6.md
> +4. Select the **Use Payment component** radio button to **Yes**.
?

2023-03-14 14:24 UTC, inesmayerMSP commented on content/integrations/prestashop-1-6.md
> +💬 Support: If you're new to accepting credit card payments, email a request to activate them to <sales@multisafepay.com>
review

2023-03-14 14:24 UTC, inesmayerMSP commented on content/integrations/prestashop-1-6.md
> +5. Set the **Tokenization** field to **YES**.
unify with above text: caps or not

2023-03-14 14:24 UTC, inesmayerMSP commented on content/integrations/prestashop-1-7.md
> +- Cards: Amex, Maestro, Mastercard, and Visa.
full stop

2023-03-14 14:24 UTC, inesmayerMSP commented on content/integrations/woocommerce.md
> +4. Select the **Payment components** checkbox.
verify. Select if more options

2023-03-21 12:19 UTC, merged