DOCS-3849: Add custom URL in the Magento 2
MultiSafepay/docs pull request #2682
Opened 2023-03-03 15:31 UTC by Rendani-MultiSafepay

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2023-03-07 14:45 UTC, Vinod-MultiSafepay requested changes
Good addition. Some small improvements can be made.

2023-03-07 14:45 UTC, Vinod-MultiSafepay commented on content/integrations/magento-2.md
> +<summary>How to set up custom URL</summary>
There are 2 custom urls to be set, the return url and the cancel url. Could you make this plural?

2023-03-07 14:45 UTC, Vinod-MultiSafepay commented on content/integrations/magento-2.md
> +5. In the **Custom redirect url after  canceling the payment** field, add your custom URL.
There are 2 custom urls, One says: `Custom redirect url after cancelling the payment`, the other one says: `Custom "Success page" url` , either one or both can be set. Please clarify that some more.

2023-03-08 10:38 UTC, Vinod-MultiSafepay approved these changes

2023-03-14 14:09 UTC, inesmayerMSP requested changes

2023-03-14 14:09 UTC, inesmayerMSP commented on content/integrations/magento-2.md
> +  - **Custom redirect url after  canceling the payment** field, **or**
delete space

2023-03-14 14:09 UTC, inesmayerMSP commented on content/integrations/magento-2.md
> +  - **Custom "Success page" url** field.
add your custom URL either to 
- the ....field or the ...field?

2023-03-16 11:59 UTC, rossthomasmsp approved these changes

2023-03-16 13:52 UTC, Daniel-MultiSafepay commented on content/integrations/magento-2.md
> +  - **Custom redirect url after  canceling the payment** field, **or**
This online MD editor suggest one empty space will do the trick to add indent to the bold line. 

https://markdownlivepreview.com/

2023-03-20 13:52 UTC, Rendani-MultiSafepay commented on content/integrations/magento-2.md
> +  - **Custom redirect url after  canceling the payment** field, **or**
@Daniel-MultiSafepay, delete space refers to the space between the text on line 174 between **after  canceling** there was double space.

2023-03-21 12:34 UTC, merged