DOCS-3875:Add Magento 2 Hyva Checkout & Megawire modules
MultiSafepay/docs pull request #2706
Opened 2023-04-11 07:59 UTC by Rendani-MultiSafepay

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2023-04-20 17:07 UTC, Daniel-MultiSafepay commented on content/integrations/magento-2.md
> +    <td>One Step Module not available</td>
This is supposed to say it is supported by default, or out of the box.

2023-04-20 17:08 UTC, Daniel-MultiSafepay requested changes

2023-04-20 17:08 UTC, Daniel-MultiSafepay commented on content/integrations/magento-2.md
> +    <td> Amasty One Step module not available.</td>
This is supposed to say it is supported by default, or out of the box.

2023-04-25 12:00 UTC, Daniel-MultiSafepay requested changes
Check my comments.

2023-04-25 12:00 UTC, Daniel-MultiSafepay commented on content/integrations/magento-2.md
> +    <td> <a href="https://hyva.io/hyva-checkout.html" target="_blank"> Hyvä Checkout</a> <i class="fa fa-external-link" style="font-size:12px;color:#8b929e"></i></td>
This is wrong. You are matching Hyva React checkout to Magewire Checkout using this link. 

Please, could you check my comments here: 

https://jira.multisafepay.com/browse/DOCS-3875?focusedCommentId=171820&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-171820

2023-05-02 14:06 UTC, Daniel-MultiSafepay commented on content/integrations/magento-2.md
> +    <td><a href=" https://docs.hyva.io/checkout/hyva-checkout/index.html " target="_blank"> Hyvä Megawire checkout</a> <i class="fa fa-external-link" style="font-size:12px;color:#8b929e"></i> </td>
Fix empty whitespaces in the href tag.

2023-05-02 14:09 UTC, Daniel-MultiSafepay commented on content/integrations/magento-2.md
> +    <td>By default,MagePlaza One Step checkout is supported. </td>
The space after the comma is missed.

2023-05-02 14:09 UTC, Daniel-MultiSafepay requested changes
Check comments.

2023-05-04 07:28 UTC, Daniel-MultiSafepay submitted a review, later dismissed

2023-05-04 07:31 UTC, Daniel-MultiSafepay requested changes
Remove block commented or explain why you need to keep it

2023-05-04 07:45 UTC, Rendani-MultiSafepay commented on content/integrations/magento-2.md
> +<!--
Hi, I keep the uncommented block if ReadMe does not interpret the HTML table tags. That way, I can quickly use the uncommented block to update the checkouts on the browser. However, should the table be interpreted right? I will remove the block.

2023-05-04 08:29 UTC, Daniel-MultiSafepay commented on content/integrations/magento-2.md
> +<!--
I have no idea how the platform used for DOCS renders the code, but as far as I know, some HTML tags are going to be stripped, but not sure which ones. 

It seems we are using markdown syntax for tables. I can't find any table being done using HTML tags. 

Please, check this as example:
- https://github.com/MultiSafepay/docs/blob/master/content/integrations/opencart.md?plain=1#L70-L82

Reference:
- https://www.markdownguide.org/extended-syntax/#tables

2023-05-04 09:04 UTC, Daniel-MultiSafepay approved these changes

2023-05-04 09:05 UTC, Daniel-MultiSafepay commented on content/integrations/magento-2.md
> +<!--
Understood. I just approved this PR. 

Is up to you if you want to remove the block commented now or later, depending on the results after the merge

2023-05-05 11:11 UTC, merged