DOCS-3960: Add new feature: Order flows
MultiSafepay/docs pull request #2830
Opened 2023-08-31 09:36 UTC by Rendani-MultiSafepay

Do the changes meet MultiSafepay Docs' Definition of Done?
- Style guide, tone of voice, and naming conventions
- Tested
- Reviewed on mobile, tablet and desktop screens
- Notified stakeholders
- Pass GitHub Actions

2023-09-12 09:13 UTC, Daniel-MultiSafepay commented
@Mike-MultiSafepay could you take care of this PR review?

2023-09-12 11:08 UTC, Mike-MultiSafepay requested changes

2023-09-12 11:08 UTC, Mike-MultiSafepay commented on content/integrations/shopware-5.md
> +If the notification hasn't been processed yet, a waiting page with a loader displays while the order is created.
This part can be removed because this is not supported in SW5

```suggestion
```

2023-09-19 09:57 UTC, Mike-MultiSafepay approved these changes

2023-09-19 10:16 UTC, merged