INTGRTN-1723: updated-text-community-integration
MultiSafepay/docs pull request #638
Opened 2020-07-23 10:21 UTC by Alex-MultiSafepay

### Basic
- We only accept documentation that is proved to work on our LIVE API
- At least 1 approval is needed before pull requests can be merged
- The article must match our Synonym word list. For external commits, a MultiSafepay employee will check
- US English must be applied
- Use bullets for numerations where the sort order doesn't matter. For chronological order, use numbers. This does not apply to changelogs
- Set link on email address.

### Text style
- Paths are written like: _Configuration → System → Plugin → MultiSafepay_
- Use single quotation marks in your Markdown code (example title: 'Title of the article')
- Use Italics for buttons, clicks, paths, etc. Do mind to close the italics before the end of a sentence followed by a period
- Numerations / bullets are punctuated with a period at the end of the numerations / bullets.
- Periods should be excluded for sentences that finish in an e-mail address (e.g. "..contact us at <example@example.com> "  )

### Images
- Screenshot recomended sizes: Width: 820px - Height: auto

2020-08-03 07:36 UTC, Alex-MultiSafepay commented
@Qadira-MultiSafepay is it now ok?

2020-09-15 11:27 UTC, Atiq-MultiSafepay requested changes

2020-09-15 11:27 UTC, Atiq-MultiSafepay commented on content/integrations/community/Community integration requirements/_index.md
> +We are happy to give a place on our documentation page if you have created an integration with us. If you would like for your project to appear on our documentation page, please contact the MultiSafe
We would be delighted to offer a place on our documentation page if you have created an integration with us. If you would like for your project to appear on our documentation page, please contact the MultiSafepay Integration Team at integration@multisafepay.com

2020-09-15 11:27 UTC, Atiq-MultiSafepay commented on content/integrations/community/Community integration requirements/_index.md
> +* The responsibility lies with the developer of the integration, and we expect you to provide customer support and maintenance of the code.
* The responsibility lies with the developer of the integration and we expect you to provide customer support and maintenance of the code.

2020-09-15 11:27 UTC, Atiq-MultiSafepay commented on content/integrations/community/Community integration requirements/_index.md
> +* On your page it should indicate that the integration was not created by MultiSafepay
* On the page it should indicate that the integration was not created by MultiSafepay

2020-09-15 11:27 UTC, Atiq-MultiSafepay commented on content/integrations/community/Community integration requirements/_index.md
> +* If MultiSafepay decides to add the integration as one of the supported integrations by MultiSafepay, we will have the authority to also remove the community integration without the breach of contra
* If MultiSafepay decides to add the integration as one of the supported integrations, we will have the authority to also remove the community integration without the breach of contract

2020-10-14 09:49 UTC, Atiq-MultiSafepay commented on content/integrations/community/Community integration requirements/_index.md
> +We are happy to give a place on our documentation page if you have created an integration with us. If you would like for your project to appear on our documentation page, please contact the MultiSafe
If you would like to share your project with us and appear on DOCS, feel free to contact the MultiSafepay Integration team at integration@multisafepay.om

2020-11-05 11:21 UTC, Atiq-MultiSafepay approved these changes

2020-11-05 11:21 UTC, merged