DOCS-1515: Add new Magento 2 plugin page
MultiSafepay/docs pull request #655
Opened 2020-08-20 17:21 UTC by Vinod-MultiSafepay

@Atiq-MultiSafepay Please provide some feedback on the english and grammar and such

2020-08-24 10:39 UTC, Atiq-MultiSafepay commented on content/integrations/plugins/magento2/beta.md
> +- check the rights on files correctly. Our files can be found at vendor/multisafepay
The 'rights' on files correctly. Our files can be found at vendor/MultiSafepay

2020-08-24 10:39 UTC, Atiq-MultiSafepay commented on content/integrations/plugins/magento2/beta.md
> +Depending on your webserver/webshop configuration you also need to check:
Depending on your webserver/webshop configuration, you also need to check:

2020-08-24 10:40 UTC, Atiq-MultiSafepay commented on content/integrations/plugins/magento2/beta.md
> +You have installed and configured the plugin successfully. If you have any questions regarding the plugin, feel free to contact our Integration Team at <integration@multisafepay.com> or start a discu
Integration team

2020-08-24 14:20 UTC, Vinod-MultiSafepay commented on content/integrations/plugins/magento2/beta.md
> +- check the rights on files correctly. Our files can be found at vendor/multisafepay
> The 'rights' on files correctly. Our files can be found at _vendor/MultiSafepay_

We have to use the vendor name of MultiSafepay here, which is in small letters and non-capitals:
https://packagist.org/packages/multisafepay/

2020-08-31 08:06 UTC, Qadira-MultiSafepay approved these changes

2020-09-04 09:36 UTC, Atiq-MultiSafepay requested changes

2020-09-04 09:36 UTC, Atiq-MultiSafepay commented on content/integrations/plugins/magento2/beta.md
> +**It is possible to have the old and the new plugin installed at the same time. To avoid confusion however, we recommend completely uninstalling the old module first, before installing the new one.**
**It is possible to have both the old and the new plugin installed at the same time. To avoid confusion however, we recommend completely uninstalling the old module first, before installing the new one.**

2020-09-04 13:28 UTC, Jasper-MultiSafepay approved these changes

2020-09-04 13:28 UTC, merged