Docs plglts2
MultiSafepay/docs pull request #658
Opened 2020-08-26 09:29 UTC by Lars-MultiSafepay

### Basic
- We only accept documentation that is proved to work on our LIVE API
- At least 1 approval is needed before pull requests can be merged
- The article must match our Synonym word list. For external commits, a MultiSafepay employee will check
- US English must be applied
- Use bullets for numerations where the sort order doesn't matter. For chronological order, use numbers. This does not apply to changelogs
- Set link on email address.

### Text style
- Paths are written like: _Configuration → System → Plugin → MultiSafepay_
- Use single quotation marks in your Markdown code (example title: 'Title of the article')
- Use Italics for buttons, clicks, paths, etc. Do mind to close the italics before the end of a sentence followed by a period
- Numerations / bullets are punctuated with a period at the end of the numerations / bullets.
- Periods should be excluded for sentences that finish in an e-mail address (e.g. "..contact us at <example@example.com> "  )

### Images
- Screenshot recomended sizes: Width: 820px - Height: auto

2020-08-26 10:27 UTC, Atiq-MultiSafepay requested changes

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/change-environment.md
> +You sure can. In the settings page click on _Environment & API key_. You will be redirected to another page.
Yes. On the settings page click on _Environment & API key_. You will be redirected to another page.

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/change-environment.md
> +Here you can update the API key or the environment, or both.
Here you can update the API key, the environment, or both.

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/disable-payment-methods.md
> +If you want different payment methods disabled for different languages, you can make these adjustments in the dropdown menu under the _Payment methods ordering_ header where you first need to select
If you want different payment methods disabled for different languages, you can make these adjustments in the drop-down menu under the _Payment methods ordering_ header where you first need to select a country and then make changes on a per language basis. _Default_ is used if no specific rule-set for a language is found.

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/disable-payment-methods.md
> +Are you missing any payment methods? Make sure that the payment methods are first enabled in the [MultiSafepay Control](https://docs.multisafepay.com/tools/multisafepay-control/) and then go to the s
Are you missing any payment methods? Make sure that the payment methods are first enabled in the [MultiSafepay Control](https://docs.multisafepay.com/tools/multisafepay-control/) and then go to the settings page of our Lightspeed app and enable the respective payment method there again. By default, newly activated payment methods in the MultiSafepay Control are disabled in the Lightspeed MultiSafepay Payments settings, so you need to enable them in both environments.

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/inline-buy-button.md
> +Yes, if you want to put an extra buy button near the selected payment method you can configure this in the settings page by going to _Inline Buy button_ and selecting _Show inline_ option.
Yes, if you want to put an extra buy button near the selected payment method, you can configure this in the settings page by going to _Inline Buy button_ and selecting _Show inline_ option.

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/inline-news-letter.md
> +Yes! If you want to put a newsletter checkmark near the selected payment method you can do so by going to _Inline newsletter_ on your settings page and choosing _Show inline_. The inline buy has to b
Yes. If you would like to put a newsletter check-mark near the selected payment method you can do so by going to _Inline newsletter_ on your settings page and choosing _Show inline_. The inline buy has to be enabled.

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/maximal-order-amount.md
> +_For example, iDEAL with a maximum value of 1500 means that iDEAL will not be displayed in the checkout unless the total order amount is less then 15.00 EUR._
_For example, iDEAL with a maximum value of 1500 means that iDEAL will not be displayed in the checkout unless the total order amount is less then 15,00 EUR._

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/minimal-order-amount.md
> +Yes, you can change the minimal order amount for a payment method to be displayed to the customer. To do so, you have to open the payment method in the _Payment methods ordering_ list by clicking on
Yes, you can change the minimum order amount for a payment method to be displayed to the customer. To do so, you have to open the payment method in the _Payment methods ordering_ list by clicking on the "+" sign and then entering an amount in EUR cents.

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/minimal-order-amount.md
> +_For example, if you input a minimal value of 1500 for iDEAL, it means that iDEAL will not be displayed in the checkout unless the total order amount equals 15.00 EUR or more._
_For example, if you input a minimal value of 1500 for iDEAL, it means that iDEAL will not be displayed in the checkout unless the total order amount equals 15,00 EUR or more._

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/minimal-order-amount.md
> +If you want different minimal order amounts for different languages you can configure this as well. In the dropdown menu under the _Payment methods ordering_ header you can select a country and make
If you want different minimum order amounts for different languages you can configure this as well. In the drop-down menu under the _Payment methods ordering_ header, you can select a country and make a change on a per language basis.

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/order-payment-methods.md
> +If you want a different payment method order for different languages, you can configure it here as well. In the dropdown menu under the _Payment methods ordering_ header you can select a country and
If you want a different payment method order for different languages, you can configure it here as well. In the drop-down menu under the _Payment methods ordering_ header you can select a country and make a change on a per language basis.

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/shop_id.md
> +2. Click in the bottom left corner on help.
2. Click in the bottom left corner on _Help_

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/shop_id.md
> +1. Log into the /admin area of you webshopapp.
1. Log into the /admin area of you webshop app

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/manual.md
> +For the optimal experience of the user we included some Javascript and use our own images. This allows us to add, for example, a dropdown for iDEAL and our own icons for other payment methods. Some t
For the optimal experience of the user we included some Javascript and use our own images. This allows us to add, for example, a drop-down for iDEAL and our own icons for other payment methods. Some themes or users added scripts can cause issue, such as missing images for payment methods. To resolve these issue can require a developer.

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/manual.md
> +The application is tested using the default, onestep and onepage checkout using the default thema.
The application is tested using the default, onestep and onepage checkout using the default theme.

2020-08-26 10:27 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/manual.md
> +But don't worry if the javascript files are not loaded, all payment methods will keep working. And if you want to use our payment icons you can find them [here!](https://github.com/MultiSafepay/Multi
But don't worry if the javascript files are not loaded, all payment methods will keep working. If you want to use our payment icons you can find them [here!](https://github.com/MultiSafepay/MultiSafepay-icons)

2020-08-27 06:15 UTC, Lars-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/disable-payment-methods.md
> +If you want different payment methods disabled for different languages, you can make these adjustments in the dropdown menu under the _Payment methods ordering_ header where you first need to select
I resolved all comments, can you take another look?

2020-09-07 07:23 UTC, Lars-MultiSafepay commented
Not all banned words can be changed due to lightspeeds naming conventions.

2020-09-07 08:39 UTC, Atiq-MultiSafepay requested changes

2020-09-07 08:39 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/change-environment.md
> +Here you can update the API key, the environment, or both.
On this page, the API key, environment, or both can be updated.

2020-09-14 08:46 UTC, Qadira-MultiSafepay approved these changes

2020-09-14 13:24 UTC, Atiq-MultiSafepay requested changes

2020-09-14 13:24 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/manual.md
> +But don't worry if the javascript files are not loaded, all payment methods will keep working. If you want to use our payment icons you can find them [here!](https://github.com/MultiSafepay/MultiSafe
But don't worry if the javascript files are not loaded, all payment methods will continue to work. If you want to use our payment icons you can find them [here!](https://github.com/MultiSafepay/MultiSafepay-icons)

2020-09-15 07:47 UTC, Atiq-MultiSafepay approved these changes

2020-09-15 07:47 UTC, merged