DOCS-1434: fixed-ga-mistake
MultiSafepay/docs pull request #675
Opened 2020-09-03 09:05 UTC by Alex-MultiSafepay

### Basic
- We only accept documentation that is proved to work on our LIVE API
- At least 1 approval is needed before pull requests can be merged
- The article must match our Synonym word list. For external commits, a MultiSafepay employee will check
- US English must be applied
- Use bullets for numerations where the sort order doesn't matter. For chronological order, use numbers. This does not apply to changelogs
- Set link on email address.

### Text style
- Paths are written like: _Configuration → System → Plugin → MultiSafepay_
- Use single quotation marks in your Markdown code (example title: 'Title of the article')
- Use Italics for buttons, clicks, paths, etc. Do mind to close the italics before the end of a sentence followed by a period
- Numerations / bullets are punctuated with a period at the end of the numerations / bullets.
- Periods should be excluded for sentences that finish in an e-mail address (e.g. "..contact us at <example@example.com> "  )

### Images
- Screenshot recomended sizes: Width: 820px - Height: auto

2020-09-14 08:41 UTC, Qadira-MultiSafepay approved these changes

2020-09-14 13:21 UTC, Atiq-MultiSafepay requested changes

2020-09-14 13:21 UTC, Atiq-MultiSafepay commented on content/faq/api/google-analytics-tracking.md
> +For direct orders (e.g. iDEAL direct, some cases of Klarna, AfterPay, etc.), there is NO tracking available, as customers will not pass through a MultiSafepay page after checkout and before the succe
For direct orders (e.g. iDEAL direct, some cases of Klarna, AfterPay, etc.), there is __no__ tracking available, as customers will not pass through a MultiSafepay page after checkout and before the successful payment page.

2020-09-14 13:40 UTC, Alex-MultiSafepay commented on content/faq/api/google-analytics-tracking.md
> +For direct orders (e.g. iDEAL direct, some cases of Klarna, AfterPay, etc.), there is NO tracking available, as customers will not pass through a MultiSafepay page after checkout and before the succe
done

2020-09-22 08:52 UTC, Alex-MultiSafepay commented
@Qadira-MultiSafepay @Atiq-MultiSafepay is it now ok? can someone approve it and merge it?

2020-09-22 10:45 UTC, merged