Docs 1512
MultiSafepay/docs pull request #779
Opened 2020-10-15 13:45 UTC by Jelle-Msp

### Basic
- We only accept documentation that is proved to work on our LIVE API
- At least 1 approval is needed before pull requests can be merged
- The article must match our Synonym word list. For external commits, a MultiSafepay employee will check
- US English must be applied
- Use bullets for numerations where the sort order doesn't matter. For chronological order, use numbers. This does not apply to changelogs
- Set link on email address.

### Text style
- Paths are written like: _Configuration → System → Plugin → MultiSafepay_
- Use single quotation marks in your Markdown code (example title: 'Title of the article')
- Use Italics for buttons, clicks, paths, etc. Do mind to close the italics before the end of a sentence followed by a period
- Numerations / bullets are punctuated with a period at the end of the numerations / bullets.
- Periods should be excluded for sentences that finish in an e-mail address (e.g. "..contact us at <example@example.com> "  )

### Images
- Screenshot recomended sizes: Width: 820px - Height: auto

2020-11-10 15:08 UTC, Atiq-MultiSafepay requested changes

2020-11-10 15:08 UTC, Atiq-MultiSafepay commented on content/integrations/accounting and bookkeeping/Snelstart/_index.md
> +snelstart supports one specific export formats. This is:
Snelstart supports one specific export format. This is:

2020-11-10 15:08 UTC, Atiq-MultiSafepay commented on content/integrations/accounting and bookkeeping/Snelstart/_index.md
> +If you would like to import a MultiSafepay accountant export, we would like to kindly ask you to visit our partner's website. [Snelstart](https://www.snelstart.nl/klantenservice) will assist you dire
If you would like to import a MultiSafepay accountant export, we would like to kindly ask you to visit our partner's website [Snelstart](https://www.snelstart.nl/klantenservice) will assist you directly in this.

2020-11-11 15:50 UTC, Qadira-MultiSafepay approved these changes

2020-11-11 15:51 UTC, Atiq-MultiSafepay approved these changes

2020-11-11 15:51 UTC, merged