DOCS-1824: Adds why some payment methods are not visible in checkout for Magento 2
MultiSafepay/docs pull request #914
Opened 2020-12-22 10:30 UTC by Atiq-MultiSafepay

2020-12-23 10:20 UTC, Vinod-MultiSafepay requested changes
What about:

- The payment method has been enabled in the wrong store view

2021-01-05 17:33 UTC, Kris-MultiSafepay reviewed
Please revise

2021-01-06 10:22 UTC, Kris-MultiSafepay commented on content/integrations/plugins/magento2/old/faq/why-is-a-specific-payment-method-not-visible-in-my-checkout.md
> +When you enabled a payment method, it should always be visible, even when your API key is incorrect.
When you enabled a payment method, it should always be visible, even when your API key is incorrect.
```suggestion
When you enabled a payment method, it should always be visible, even when your API Key is incorrect.
```

2021-01-11 12:36 UTC, Atiq-MultiSafepay commented on content/integrations/plugins/magento2/old/faq/why-is-a-specific-payment-method-not-visible-in-my-checkout.md
> +Payment methods may also not be visible in the checkout due to the following:
I will create an individual ticket to change this. Currently, i get a merge conflict in visual processing a change. All other suggested commits have been pushed.

2021-02-01 18:16 UTC, Kris-MultiSafepay approved these changes

2021-02-01 18:16 UTC, Kris-MultiSafepay commented on content/integrations/plugins/magento2/old/faq/why-is-a-specific-payment-method-not-visible-in-my-checkout.md
> +When you enabled a payment method, it should always be visible, even when your API Key is incorrect.
```suggestion
When you enabled a payment method, it should always be visible, even when your API key is incorrect.
```

2021-02-01 18:18 UTC, merged