DOCS-1624: Adds description for items and shopping_cart parameters
MultiSafepay/docs pull request #965
Opened 2021-01-12 09:40 UTC by Atiq-MultiSafepay

2021-01-18 08:09 UTC, Kris-MultiSafepay requested changes
Given that the request includes an array of items (objects) that have 7 members, I do not understand why only one of its members is specified. I would like to see the documentation for all parameters including required/optional tags.

2021-01-18 13:12 UTC, Atiq-MultiSafepay commented
@Kris-MultiSafepay  Can you elaborate on your comment in Git and provide an example please?

2021-02-01 18:27 UTC, Kris-MultiSafepay commented
"items": [
            {
                "name": "Geometric Candle Holders",
                "description": "",
                "unit_price": "90",
                "quantity": "1",
                "merchant_item_id": "hdd006",
                "tax_table_selector": "BTW0",
                "weight": {
                    "unit": "KG",
                    "value": "1"

That's the object you are documenting. None of its members are included in your documentation.

2021-03-17 15:32 UTC, Kris-MultiSafepay approved these changes

2021-03-17 15:32 UTC, merged