DOCS-1691: Adds instructions about missing logos for Lightspeed
MultiSafepay/docs pull request #975
Opened 2021-01-15 09:30 UTC by Atiq-MultiSafepay

2021-01-18 20:31 UTC, Kris-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/missing-payment-method-logos.md
> +Payment method logos may be missing due to a theme that is causing them to not appear on your Lightspeed webiste. This can easily be fixed by following these instructions:
```suggestion
Payment method logos may be missing due to a theme that is causing them to not appear on your Lightspeed website. This can easily be fixed by following these instructions:
```

2021-01-18 20:42 UTC, Kris-MultiSafepay requested changes

2021-01-18 20:42 UTC, Kris-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/missing-payment-method-logos.md
> +2. Rename the file with caps lock formatting e.g applepay.png -> APPLEPAY.png
```suggestion
2. Rename the file with upper case formatting e.g applepay.png -> APPLEPAY.png
```

2021-01-18 20:42 UTC, Kris-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/missing-payment-method-logos.md
> +3. Place the image file in _Design_ -> _Thema editor_ -> _Geavanceerd_ -> _Code bewerken_ -> _Assests_
```suggestion
3. Place the image file in _Design_ -> _Thema editor_ -> _Geavanceerd_ -> _Code bewerken_ -> _Assests_
```

Does Lightspeed have an English language setting? If yes, please use the English labels

2021-01-18 20:42 UTC, Kris-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/missing-payment-method-logos.md
> +_Please note that changes will not occur automatically and may take time to come into effect._
I believe the changes will occur naturally but take some time as the theme is not updated automatically. By stating that the changes do not occur automatically we suggest the user has to perform manual actions for the changes to occur.

2021-01-19 12:30 UTC, Atiq-MultiSafepay reviewed
@Kris-MultiSafepay  Changes have been made

2021-02-03 08:39 UTC, Kris-MultiSafepay approved these changes

2021-02-03 08:39 UTC, merged