DOCS: lightspeed login text
MultiSafepay/docs pull request #985
Opened 2021-01-19 08:10 UTC by Lars-MultiSafepay

### Basic
- We only accept documentation that is proved to work on our LIVE API
- At least 1 approval is needed before pull requests can be merged
- The article must match our Synonym word list. For external commits, a MultiSafepay employee will check
- US English must be applied
- Use bullets for numerations where the sort order doesn't matter. For chronological order, use numbers. This does not apply to changelogs
- Set link on email address.

### Text style
- Paths are written like: _Configuration → System → Plugin → MultiSafepay_
- Use single quotation marks in your Markdown code (example title: 'Title of the article')
- Use Italics for buttons, clicks, paths, etc. Do mind to close the italics before the end of a sentence followed by a period
- Numerations / bullets are punctuated with a period at the end of the numerations / bullets.
- Periods should be excluded for sentences that finish in an e-mail address (e.g. "..contact us at <example@example.com> "  )

### Images
- Screenshot recomended sizes: Width: 820px - Height: auto

2021-01-19 10:24 UTC, Atiq-MultiSafepay requested changes
@Lars-MultiSafepay I've added a few corrections to the text.
Also, I believe it may be better to explain the instructions step-by-step. Let me know your thoughts.

2021-01-19 10:24 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/how-to-login.md
> +In early 2021 we have changed how our login system works for the MultiSafepay Payment app for lightspeed eCom. Our old system was password based, our new system uses the Single Sign On provided by li
In early 2021, we have changed how our login system works for the MultiSafepay Payment app for Lightspeed eCom. Our old system was password based, although now our new system uses the Single Sign On provided by Lightspeed. This means you can directly login via Lightspeed eCom store to our settings page of the app.

2021-01-19 10:24 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/how-to-login.md
> +To login using the new system you have to use our app store page. Login to the /admin section of your lightspeed store. Go to apps, my apps / "aangeschafte apps" and click on the name of our app, Mul
To login using the new system you have to use our app store page. Login to the /admin section of your Lightspeed store. Go to apps, my apps / "aangeschafte apps" and click on the name of our app, MultiSafepay Payments. This should open the app store page. Alternatively paste "/admin/store/apps/1517" after the base url your store.

2021-01-19 10:24 UTC, Atiq-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/how-to-login.md
> +On the store page click on "Goto app" / "Ga naar app" And you will be able to access your settings page.
On the store page click on "Goto app" / "Ga naar app" and you will be able to access your settings page.

2021-01-20 12:54 UTC, Lars-MultiSafepay commented
@Jasper-MultiSafepay added images

2021-01-20 14:31 UTC, Kris-MultiSafepay requested changes

2021-01-20 14:31 UTC, Kris-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/how-to-login.md
> +In early 2021, we have changed how our login system works for the MultiSafepay Payment app for Lightspeed eCom. Our old system was password based, although now our new system uses the Single Sign On
```suggestion
In early 2021, we have changed the login method for the MultiSafepay Payment app for Lightspeed eCom. The old login method was password-based, while the new method uses the single sign-on provided by Lightspeed. This means you can directly log in via the Lightspeed eCom store to our settings page of the app.
```
login = noun
log in =  verb

2021-01-20 14:31 UTC, Kris-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/how-to-login.md
> +To login using the new system you have to use our app store page. Login to the /admin section of your Lightspeed store.
```suggestion
To log in using the new method you have to use our app store page. Login to the /admin section of your Lightspeed store. 
```

2021-01-21 06:35 UTC, Lars-MultiSafepay commented on content/integrations/hosted/lightspeed_app/faq/how-to-login.md
> +In early 2021, we have changed how our login system works for the MultiSafepay Payment app for Lightspeed eCom. Our old system was password based, although now our new system uses the Single Sign On
👍 ty

2021-01-21 08:16 UTC, Jasper-MultiSafepay approved these changes

2021-01-21 08:16 UTC, merged