DOCS-1620: Adds credit card components to Tools
MultiSafepay/docs pull request #996
Opened 2021-01-25 08:07 UTC by Atiq-MultiSafepay

2021-01-25 11:47 UTC, Jasper-MultiSafepay requested changes
@Atiq-MultiSafepay 
Is there a way to also include the SVG flowdiagram?

2021-01-25 12:02 UTC, Kris-MultiSafepay requested changes

2021-01-25 12:02 UTC, Kris-MultiSafepay commented on content/tools/credit-card-components/credit-card-components.md
> +This payload can be sent with a [direct CREDITCARD transaction request]((https://docs.multisafepay.com/api/#create-a-direct-order))
```suggestion
This payload can be sent with a [direct CREDITCARD transaction request](https://docs.multisafepay.com/api/#create-a-direct-order)
```

2021-02-04 15:52 UTC, Kris-MultiSafepay approved these changes

2021-02-04 15:52 UTC, Kris-MultiSafepay commented on content/tools/credit-card-components/credit-card-components.md
> +All requests to the MultiSafepay API endpoint require authentication. This is provided by including an API key as an HTTP header in your request. Each website has its own API key so if you are operat
```suggestion
All requests to the MultiSafepay API endpoint require authentication. This is provided by including an API key as an HTTP header in your request. Each website has its own API key so if you are operating multiple websites, be sure to use the correct API key for each site. You can find your API key under the _Website settings_ in your [MultiSafepay Control](https://merchant.multisafepay.com/)<br> 
```

2021-02-04 15:52 UTC, Kris-MultiSafepay commented on content/tools/credit-card-components/credit-card-components.md
> +The Test environment is useful for developing and testing the Credit card component integration with our API. Once the integration has been developed, processing real transactions is as simple as cha
```suggestion
The Test environment is useful for developing and testing the Credit card component integration with our API. Once you have developed the integration, processing real transactions is as simple as changing the API endpoint and using your live API key.<br>
```

2021-02-04 15:52 UTC, Kris-MultiSafepay commented on content/tools/credit-card-components/credit-card-components.md
> +`GET /v1/connect/auth/api_token`
```suggestion
`GET https://api.multisafepay.com/v1/connect/auth/api_token`
```
Specify full API endpoint

2021-02-04 15:52 UTC, Kris-MultiSafepay commented on content/tools/credit-card-components/credit-card-components.md
> +`env` -> test/live, decides the API mode<br>
This doesn't work
```suggestion
`env` -> test/live, decides the API mode {{< br >}} 
```

2021-02-04 15:52 UTC, Kris-MultiSafepay commented on content/tools/credit-card-components/credit-card-components.md
> +`apiToken` -> api_token from step 1<br>
```suggestion
`apiToken` -> api_token from step 1 {{< br >}} 
```

2021-02-04 15:52 UTC, Kris-MultiSafepay commented on content/tools/credit-card-components/credit-card-components.md
> +* components.js<br>
```suggestion
**components.js**
```

2021-02-04 15:52 UTC, Kris-MultiSafepay commented on content/tools/credit-card-components/credit-card-components.md
> +* components.css<br>
```suggestion
**components.css**
```

2021-02-04 15:52 UTC, Kris-MultiSafepay commented on content/tools/credit-card-components/credit-card-components.md
> +{{< responsive_svg src="/diagrams/svg/CCC_CSS" alt="TEST" align="center" >}}
This breaks on mobile, put it live now but will have to fix later.

2021-02-04 15:52 UTC, Kris-MultiSafepay commented on content/tools/credit-card-components/credit-card-components.md
> +
```suggestion
```

2021-02-04 15:52 UTC, Kris-MultiSafepay commented on content/tools/credit-card-components/credit-card-components.md
> +
```suggestion
```

2021-02-04 15:54 UTC, Kris-MultiSafepay approved these changes

2021-02-04 15:55 UTC, merged